// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: discovery/v1/discovery.proto

package discoveryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerUpdate_UpdateType int32

const (
	PeerUpdate_PEER_JOINED  PeerUpdate_UpdateType = 0
	PeerUpdate_PEER_LEFT    PeerUpdate_UpdateType = 1
	PeerUpdate_PEER_UPDATED PeerUpdate_UpdateType = 2
)

// Enum value maps for PeerUpdate_UpdateType.
var (
	PeerUpdate_UpdateType_name = map[int32]string{
		0: "PEER_JOINED",
		1: "PEER_LEFT",
		2: "PEER_UPDATED",
	}
	PeerUpdate_UpdateType_value = map[string]int32{
		"PEER_JOINED":  0,
		"PEER_LEFT":    1,
		"PEER_UPDATED": 2,
	}
)

func (x PeerUpdate_UpdateType) Enum() *PeerUpdate_UpdateType {
	p := new(PeerUpdate_UpdateType)
	*p = x
	return p
}

func (x PeerUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_v1_discovery_proto_enumTypes[0].Descriptor()
}

func (PeerUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_discovery_v1_discovery_proto_enumTypes[0]
}

func (x PeerUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdate_UpdateType.Descriptor instead.
func (PeerUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{7, 0}
}

type AnnounceNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`                          // multiaddrs: /ip4/1.2.3.4/tcp/4001
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Ed25519 public key (base64)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceNodeRequest) Reset() {
	*x = AnnounceNodeRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceNodeRequest) ProtoMessage() {}

func (x *AnnounceNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceNodeRequest.ProtoReflect.Descriptor instead.
func (*AnnounceNodeRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *AnnounceNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AnnounceNodeRequest) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *AnnounceNodeRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AnnounceNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AnnouncedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=announced_at,json=announcedAt,proto3" json:"announced_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnounceNodeResponse) Reset() {
	*x = AnnounceNodeResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnounceNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnounceNodeResponse) ProtoMessage() {}

func (x *AnnounceNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnounceNodeResponse.ProtoReflect.Descriptor instead.
func (*AnnounceNodeResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *AnnounceNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AnnounceNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnnounceNodeResponse) GetAnnouncedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AnnouncedAt
	}
	return nil
}

type FindPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // find peers close to this node ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                // max number of peers to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPeersRequest) Reset() {
	*x = FindPeersRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPeersRequest) ProtoMessage() {}

func (x *FindPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPeersRequest.ProtoReflect.Descriptor instead.
func (*FindPeersRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *FindPeersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FindPeersRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FindPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindPeersResponse) Reset() {
	*x = FindPeersResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindPeersResponse) ProtoMessage() {}

func (x *FindPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindPeersResponse.ProtoReflect.Descriptor instead.
func (*FindPeersResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *FindPeersResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeInfoRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetNodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeInfoResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

type StreamPeerUpdatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPeerUpdatesRequest) Reset() {
	*x = StreamPeerUpdatesRequest{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPeerUpdatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPeerUpdatesRequest) ProtoMessage() {}

func (x *StreamPeerUpdatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPeerUpdatesRequest.ProtoReflect.Descriptor instead.
func (*StreamPeerUpdatesRequest) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *StreamPeerUpdatesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerUpdate_UpdateType  `protobuf:"varint,1,opt,name=type,proto3,enum=discovery.v1.PeerUpdate_UpdateType" json:"type,omitempty"`
	Peer          *PeerInfo              `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *PeerUpdate) GetType() PeerUpdate_UpdateType {
	if x != nil {
		return x.Type
	}
	return PeerUpdate_PEER_JOINED
}

func (x *PeerUpdate) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *PeerUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	IsRelay       bool                   `protobuf:"varint,4,opt,name=is_relay,json=isRelay,proto3" json:"is_relay,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_discovery_v1_discovery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_v1_discovery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_discovery_v1_discovery_proto_rawDescGZIP(), []int{8}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetIsRelay() bool {
	if x != nil {
		return x.IsRelay
	}
	return false
}

func (x *PeerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

var File_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\x1cdiscovery/v1/discovery.proto\x12\fdiscovery.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x13AnnounceNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"\x89\x01\n" +
	"\x14AnnounceNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\fannounced_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vannouncedAt\"A\n" +
	"\x10FindPeersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"A\n" +
	"\x11FindPeersResponse\x12,\n" +
	"\x05peers\x18\x01 \x03(\v2\x16.discovery.v1.PeerInfoR\x05peers\"-\n" +
	"\x12GetNodeInfoRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"A\n" +
	"\x13GetNodeInfoResponse\x12*\n" +
	"\x04peer\x18\x01 \x01(\v2\x16.discovery.v1.PeerInfoR\x04peer\"3\n" +
	"\x18StreamPeerUpdatesRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xeb\x01\n" +
	"\n" +
	"PeerUpdate\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.discovery.v1.PeerUpdate.UpdateTypeR\x04type\x12*\n" +
	"\x04peer\x18\x02 \x01(\v2\x16.discovery.v1.PeerInfoR\x04peer\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\">\n" +
	"\n" +
	"UpdateType\x12\x0f\n" +
	"\vPEER_JOINED\x10\x00\x12\r\n" +
	"\tPEER_LEFT\x10\x01\x12\x10\n" +
	"\fPEER_UPDATED\x10\x02\"\xac\x01\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x19\n" +
	"\bis_relay\x18\x04 \x01(\bR\aisRelay\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen2\xe4\x02\n" +
	"\x10DiscoveryService\x12U\n" +
	"\fAnnounceNode\x12!.discovery.v1.AnnounceNodeRequest\x1a\".discovery.v1.AnnounceNodeResponse\x12L\n" +
	"\tFindPeers\x12\x1e.discovery.v1.FindPeersRequest\x1a\x1f.discovery.v1.FindPeersResponse\x12R\n" +
	"\vGetNodeInfo\x12 .discovery.v1.GetNodeInfoRequest\x1a!.discovery.v1.GetNodeInfoResponse\x12W\n" +
	"\x11StreamPeerUpdates\x12&.discovery.v1.StreamPeerUpdatesRequest\x1a\x18.discovery.v1.PeerUpdate0\x01BDZBgithub.com/saitddundar/vinctum-core/proto/discovery/v1;discoveryv1b\x06proto3"

var (
	file_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_discovery_v1_discovery_proto_rawDescData []byte
)

func file_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_discovery_v1_discovery_proto_rawDescData
}

var file_discovery_v1_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_discovery_v1_discovery_proto_goTypes = []any{
	(PeerUpdate_UpdateType)(0),       // 0: discovery.v1.PeerUpdate.UpdateType
	(*AnnounceNodeRequest)(nil),      // 1: discovery.v1.AnnounceNodeRequest
	(*AnnounceNodeResponse)(nil),     // 2: discovery.v1.AnnounceNodeResponse
	(*FindPeersRequest)(nil),         // 3: discovery.v1.FindPeersRequest
	(*FindPeersResponse)(nil),        // 4: discovery.v1.FindPeersResponse
	(*GetNodeInfoRequest)(nil),       // 5: discovery.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),      // 6: discovery.v1.GetNodeInfoResponse
	(*StreamPeerUpdatesRequest)(nil), // 7: discovery.v1.StreamPeerUpdatesRequest
	(*PeerUpdate)(nil),               // 8: discovery.v1.PeerUpdate
	(*PeerInfo)(nil),                 // 9: discovery.v1.PeerInfo
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_discovery_v1_discovery_proto_depIdxs = []int32{
	10, // 0: discovery.v1.AnnounceNodeResponse.announced_at:type_name -> google.protobuf.Timestamp
	9,  // 1: discovery.v1.FindPeersResponse.peers:type_name -> discovery.v1.PeerInfo
	9,  // 2: discovery.v1.GetNodeInfoResponse.peer:type_name -> discovery.v1.PeerInfo
	0,  // 3: discovery.v1.PeerUpdate.type:type_name -> discovery.v1.PeerUpdate.UpdateType
	9,  // 4: discovery.v1.PeerUpdate.peer:type_name -> discovery.v1.PeerInfo
	10, // 5: discovery.v1.PeerUpdate.timestamp:type_name -> google.protobuf.Timestamp
	10, // 6: discovery.v1.PeerInfo.last_seen:type_name -> google.protobuf.Timestamp
	1,  // 7: discovery.v1.DiscoveryService.AnnounceNode:input_type -> discovery.v1.AnnounceNodeRequest
	3,  // 8: discovery.v1.DiscoveryService.FindPeers:input_type -> discovery.v1.FindPeersRequest
	5,  // 9: discovery.v1.DiscoveryService.GetNodeInfo:input_type -> discovery.v1.GetNodeInfoRequest
	7,  // 10: discovery.v1.DiscoveryService.StreamPeerUpdates:input_type -> discovery.v1.StreamPeerUpdatesRequest
	2,  // 11: discovery.v1.DiscoveryService.AnnounceNode:output_type -> discovery.v1.AnnounceNodeResponse
	4,  // 12: discovery.v1.DiscoveryService.FindPeers:output_type -> discovery.v1.FindPeersResponse
	6,  // 13: discovery.v1.DiscoveryService.GetNodeInfo:output_type -> discovery.v1.GetNodeInfoResponse
	8,  // 14: discovery.v1.DiscoveryService.StreamPeerUpdates:output_type -> discovery.v1.PeerUpdate
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_discovery_v1_discovery_proto_init() }
func file_discovery_v1_discovery_proto_init() {
	if File_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_v1_discovery_proto_rawDesc), len(file_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_v1_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_v1_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_discovery_v1_discovery_proto = out.File
	file_discovery_v1_discovery_proto_goTypes = nil
	file_discovery_v1_discovery_proto_depIdxs = nil
}
