// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: discovery/v1/discovery.proto

package discoveryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscoveryService_AnnounceNode_FullMethodName      = "/discovery.v1.DiscoveryService/AnnounceNode"
	DiscoveryService_FindPeers_FullMethodName         = "/discovery.v1.DiscoveryService/FindPeers"
	DiscoveryService_GetNodeInfo_FullMethodName       = "/discovery.v1.DiscoveryService/GetNodeInfo"
	DiscoveryService_StreamPeerUpdates_FullMethodName = "/discovery.v1.DiscoveryService/StreamPeerUpdates"
)

// DiscoveryServiceClient is the client API for DiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryServiceClient interface {
	AnnounceNode(ctx context.Context, in *AnnounceNodeRequest, opts ...grpc.CallOption) (*AnnounceNodeResponse, error)
	FindPeers(ctx context.Context, in *FindPeersRequest, opts ...grpc.CallOption) (*FindPeersResponse, error)
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	StreamPeerUpdates(ctx context.Context, in *StreamPeerUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerUpdate], error)
}

type discoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryServiceClient(cc grpc.ClientConnInterface) DiscoveryServiceClient {
	return &discoveryServiceClient{cc}
}

func (c *discoveryServiceClient) AnnounceNode(ctx context.Context, in *AnnounceNodeRequest, opts ...grpc.CallOption) (*AnnounceNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnnounceNodeResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_AnnounceNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) FindPeers(ctx context.Context, in *FindPeersRequest, opts ...grpc.CallOption) (*FindPeersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindPeersResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_FindPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, DiscoveryService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryServiceClient) StreamPeerUpdates(ctx context.Context, in *StreamPeerUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DiscoveryService_ServiceDesc.Streams[0], DiscoveryService_StreamPeerUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPeerUpdatesRequest, PeerUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryService_StreamPeerUpdatesClient = grpc.ServerStreamingClient[PeerUpdate]

// DiscoveryServiceServer is the server API for DiscoveryService service.
// All implementations should embed UnimplementedDiscoveryServiceServer
// for forward compatibility.
type DiscoveryServiceServer interface {
	AnnounceNode(context.Context, *AnnounceNodeRequest) (*AnnounceNodeResponse, error)
	FindPeers(context.Context, *FindPeersRequest) (*FindPeersResponse, error)
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	StreamPeerUpdates(*StreamPeerUpdatesRequest, grpc.ServerStreamingServer[PeerUpdate]) error
}

// UnimplementedDiscoveryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscoveryServiceServer struct{}

func (UnimplementedDiscoveryServiceServer) AnnounceNode(context.Context, *AnnounceNodeRequest) (*AnnounceNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceNode not implemented")
}
func (UnimplementedDiscoveryServiceServer) FindPeers(context.Context, *FindPeersRequest) (*FindPeersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindPeers not implemented")
}
func (UnimplementedDiscoveryServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedDiscoveryServiceServer) StreamPeerUpdates(*StreamPeerUpdatesRequest, grpc.ServerStreamingServer[PeerUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamPeerUpdates not implemented")
}
func (UnimplementedDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServiceServer will
// result in compilation errors.
type UnsafeDiscoveryServiceServer interface {
	mustEmbedUnimplementedDiscoveryServiceServer()
}

func RegisterDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscoveryService_ServiceDesc, srv)
}

func _DiscoveryService_AnnounceNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnnounceNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).AnnounceNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_AnnounceNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).AnnounceNode(ctx, req.(*AnnounceNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_FindPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).FindPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_FindPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).FindPeers(ctx, req.(*FindPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscoveryService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryService_StreamPeerUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPeerUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DiscoveryServiceServer).StreamPeerUpdates(m, &grpc.GenericServerStream[StreamPeerUpdatesRequest, PeerUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DiscoveryService_StreamPeerUpdatesServer = grpc.ServerStreamingServer[PeerUpdate]

// DiscoveryService_ServiceDesc is the grpc.ServiceDesc for DiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "discovery.v1.DiscoveryService",
	HandlerType: (*DiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnnounceNode",
			Handler:    _DiscoveryService_AnnounceNode_Handler,
		},
		{
			MethodName: "FindPeers",
			Handler:    _DiscoveryService_FindPeers_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _DiscoveryService_GetNodeInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPeerUpdates",
			Handler:       _DiscoveryService_StreamPeerUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "discovery/v1/discovery.proto",
}
