// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transfer/v1/transfer.proto

package transferv1

import (
	v1 "github.com/saitddundar/vinctum-core/proto/routing/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferStatus int32

const (
	TransferStatus_TRANSFER_STATUS_UNSPECIFIED TransferStatus = 0
	TransferStatus_TRANSFER_STATUS_PENDING     TransferStatus = 1
	TransferStatus_TRANSFER_STATUS_IN_PROGRESS TransferStatus = 2
	TransferStatus_TRANSFER_STATUS_COMPLETED   TransferStatus = 3
	TransferStatus_TRANSFER_STATUS_FAILED      TransferStatus = 4
	TransferStatus_TRANSFER_STATUS_CANCELLED   TransferStatus = 5
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TRANSFER_STATUS_UNSPECIFIED",
		1: "TRANSFER_STATUS_PENDING",
		2: "TRANSFER_STATUS_IN_PROGRESS",
		3: "TRANSFER_STATUS_COMPLETED",
		4: "TRANSFER_STATUS_FAILED",
		5: "TRANSFER_STATUS_CANCELLED",
	}
	TransferStatus_value = map[string]int32{
		"TRANSFER_STATUS_UNSPECIFIED": 0,
		"TRANSFER_STATUS_PENDING":     1,
		"TRANSFER_STATUS_IN_PROGRESS": 2,
		"TRANSFER_STATUS_COMPLETED":   3,
		"TRANSFER_STATUS_FAILED":      4,
		"TRANSFER_STATUS_CANCELLED":   5,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_v1_transfer_proto_enumTypes[0].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_transfer_v1_transfer_proto_enumTypes[0]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

type InitiateTransferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SenderNodeId   string                 `protobuf:"bytes,1,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	ReceiverNodeId string                 `protobuf:"bytes,2,opt,name=receiver_node_id,json=receiverNodeId,proto3" json:"receiver_node_id,omitempty"`
	Filename       string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,4,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	ContentHash    string                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // SHA-256 hash of the entire payload
	// Deprecated: Marked as deprecated in transfer/v1/transfer.proto.
	EncryptionKey     string `protobuf:"bytes,6,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`              // DEPRECATED: must be empty. Chunks are E2E encrypted client-side; the server rejects requests that include a key.
	ChunkSizeBytes    int32  `protobuf:"varint,7,opt,name=chunk_size_bytes,json=chunkSizeBytes,proto3" json:"chunk_size_bytes,omitempty"`        // Size per chunk in bytes (default: 256KB)
	ReplicationFactor int32  `protobuf:"varint,8,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"` // Number of copies across the network (default: 1)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InitiateTransferRequest) Reset() {
	*x = InitiateTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransferRequest) ProtoMessage() {}

func (x *InitiateTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransferRequest.ProtoReflect.Descriptor instead.
func (*InitiateTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateTransferRequest) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *InitiateTransferRequest) GetReceiverNodeId() string {
	if x != nil {
		return x.ReceiverNodeId
	}
	return ""
}

func (x *InitiateTransferRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitiateTransferRequest) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *InitiateTransferRequest) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// Deprecated: Marked as deprecated in transfer/v1/transfer.proto.
func (x *InitiateTransferRequest) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

func (x *InitiateTransferRequest) GetChunkSizeBytes() int32 {
	if x != nil {
		return x.ChunkSizeBytes
	}
	return 0
}

func (x *InitiateTransferRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

type InitiateTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	TotalChunks   int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Status        TransferStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=transfer.v1.TransferStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RouteHops     []*v1.RouteHop         `protobuf:"bytes,5,rep,name=route_hops,json=routeHops,proto3" json:"route_hops,omitempty"` // Computed route for this transfer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateTransferResponse) Reset() {
	*x = InitiateTransferResponse{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateTransferResponse) ProtoMessage() {}

func (x *InitiateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateTransferResponse.ProtoReflect.Descriptor instead.
func (*InitiateTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateTransferResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *InitiateTransferResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *InitiateTransferResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *InitiateTransferResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InitiateTransferResponse) GetRouteHops() []*v1.RouteHop {
	if x != nil {
		return x.RouteHops
	}
	return nil
}

type SendChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                            // Ciphertext chunk (client-side AES-256-GCM); the server never sees plaintext.
	ChunkHash     string                 `protobuf:"bytes,4,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"` // SHA-256 of the ciphertext for transport integrity.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendChunkRequest) Reset() {
	*x = SendChunkRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChunkRequest) ProtoMessage() {}

func (x *SendChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChunkRequest.ProtoReflect.Descriptor instead.
func (*SendChunkRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{2}
}

func (x *SendChunkRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *SendChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *SendChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type SendChunkResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunksReceived int32                  `protobuf:"varint,2,opt,name=chunks_received,json=chunksReceived,proto3" json:"chunks_received,omitempty"`
	TotalChunks    int32                  `protobuf:"varint,3,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	Status         TransferStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=transfer.v1.TransferStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendChunkResponse) Reset() {
	*x = SendChunkResponse{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendChunkResponse) ProtoMessage() {}

func (x *SendChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendChunkResponse.ProtoReflect.Descriptor instead.
func (*SendChunkResponse) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{3}
}

func (x *SendChunkResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *SendChunkResponse) GetChunksReceived() int32 {
	if x != nil {
		return x.ChunksReceived
	}
	return 0
}

func (x *SendChunkResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *SendChunkResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

type ReceiveChunksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	StartChunk     int32                  `protobuf:"varint,2,opt,name=start_chunk,json=startChunk,proto3" json:"start_chunk,omitempty"` // Starting chunk index for resumable downloads
	ReceiverNodeId string                 `protobuf:"bytes,3,opt,name=receiver_node_id,json=receiverNodeId,proto3" json:"receiver_node_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReceiveChunksRequest) Reset() {
	*x = ReceiveChunksRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveChunksRequest) ProtoMessage() {}

func (x *ReceiveChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveChunksRequest.ProtoReflect.Descriptor instead.
func (*ReceiveChunksRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveChunksRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *ReceiveChunksRequest) GetStartChunk() int32 {
	if x != nil {
		return x.StartChunk
	}
	return 0
}

func (x *ReceiveChunksRequest) GetReceiverNodeId() string {
	if x != nil {
		return x.ReceiverNodeId
	}
	return ""
}

type DataChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ChunkHash     string                 `protobuf:"bytes,4,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	IsLast        bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataChunk) Reset() {
	*x = DataChunk{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataChunk) ProtoMessage() {}

func (x *DataChunk) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataChunk.ProtoReflect.Descriptor instead.
func (*DataChunk) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{5}
}

func (x *DataChunk) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *DataChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *DataChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataChunk) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *DataChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type GetTransferStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransferStatusRequest) Reset() {
	*x = GetTransferStatusRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferStatusRequest) ProtoMessage() {}

func (x *GetTransferStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransferStatusRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransferStatusRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type GetTransferStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransferId        string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Status            TransferStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=transfer.v1.TransferStatus" json:"status,omitempty"`
	ChunksTransferred int32                  `protobuf:"varint,3,opt,name=chunks_transferred,json=chunksTransferred,proto3" json:"chunks_transferred,omitempty"`
	TotalChunks       int32                  `protobuf:"varint,4,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	BytesTransferred  int64                  `protobuf:"varint,5,opt,name=bytes_transferred,json=bytesTransferred,proto3" json:"bytes_transferred,omitempty"`
	TotalBytes        int64                  `protobuf:"varint,6,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTransferStatusResponse) Reset() {
	*x = GetTransferStatusResponse{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransferStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransferStatusResponse) ProtoMessage() {}

func (x *GetTransferStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransferStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTransferStatusResponse) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransferStatusResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *GetTransferStatusResponse) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *GetTransferStatusResponse) GetChunksTransferred() int32 {
	if x != nil {
		return x.ChunksTransferred
	}
	return 0
}

func (x *GetTransferStatusResponse) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *GetTransferStatusResponse) GetBytesTransferred() int64 {
	if x != nil {
		return x.BytesTransferred
	}
	return 0
}

func (x *GetTransferStatusResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *GetTransferStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetTransferStatusResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListTransfersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // List transfers belonging to this node
	FilterStatus  TransferStatus         `protobuf:"varint,2,opt,name=filter_status,json=filterStatus,proto3,enum=transfer.v1.TransferStatus" json:"filter_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersRequest) Reset() {
	*x = ListTransfersRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersRequest) ProtoMessage() {}

func (x *ListTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersRequest.ProtoReflect.Descriptor instead.
func (*ListTransfersRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{8}
}

func (x *ListTransfersRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ListTransfersRequest) GetFilterStatus() TransferStatus {
	if x != nil {
		return x.FilterStatus
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

type ListTransfersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     []*TransferInfo        `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransfersResponse) Reset() {
	*x = ListTransfersResponse{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransfersResponse) ProtoMessage() {}

func (x *ListTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransfersResponse.ProtoReflect.Descriptor instead.
func (*ListTransfersResponse) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransfersResponse) GetTransfers() []*TransferInfo {
	if x != nil {
		return x.Transfers
	}
	return nil
}

type TransferInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransferId      string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	SenderNodeId    string                 `protobuf:"bytes,2,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	ReceiverNodeId  string                 `protobuf:"bytes,3,opt,name=receiver_node_id,json=receiverNodeId,proto3" json:"receiver_node_id,omitempty"`
	Filename        string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	TotalSizeBytes  int64                  `protobuf:"varint,5,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	Status          TransferStatus         `protobuf:"varint,6,opt,name=status,proto3,enum=transfer.v1.TransferStatus" json:"status,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,7,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferInfo) Reset() {
	*x = TransferInfo{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInfo) ProtoMessage() {}

func (x *TransferInfo) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInfo.ProtoReflect.Descriptor instead.
func (*TransferInfo) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{10}
}

func (x *TransferInfo) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *TransferInfo) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *TransferInfo) GetReceiverNodeId() string {
	if x != nil {
		return x.ReceiverNodeId
	}
	return ""
}

func (x *TransferInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TransferInfo) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *TransferInfo) GetStatus() TransferStatus {
	if x != nil {
		return x.Status
	}
	return TransferStatus_TRANSFER_STATUS_UNSPECIFIED
}

func (x *TransferInfo) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *TransferInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CancelTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferRequest) Reset() {
	*x = CancelTransferRequest{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferRequest) ProtoMessage() {}

func (x *CancelTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferRequest.ProtoReflect.Descriptor instead.
func (*CancelTransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{11}
}

func (x *CancelTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *CancelTransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTransferResponse) Reset() {
	*x = CancelTransferResponse{}
	mi := &file_transfer_v1_transfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTransferResponse) ProtoMessage() {}

func (x *CancelTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_v1_transfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTransferResponse.ProtoReflect.Descriptor instead.
func (*CancelTransferResponse) Descriptor() ([]byte, []int) {
	return file_transfer_v1_transfer_proto_rawDescGZIP(), []int{12}
}

func (x *CancelTransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTransferResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"\x1atransfer/v1/transfer.proto\x12\vtransfer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18routing/v1/routing.proto\"\xd6\x02\n" +
	"\x17InitiateTransferRequest\x12$\n" +
	"\x0esender_node_id\x18\x01 \x01(\tR\fsenderNodeId\x12(\n" +
	"\x10receiver_node_id\x18\x02 \x01(\tR\x0ereceiverNodeId\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12(\n" +
	"\x10total_size_bytes\x18\x04 \x01(\x03R\x0etotalSizeBytes\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12)\n" +
	"\x0eencryption_key\x18\x06 \x01(\tB\x02\x18\x01R\rencryptionKey\x12(\n" +
	"\x10chunk_size_bytes\x18\a \x01(\x05R\x0echunkSizeBytes\x12-\n" +
	"\x12replication_factor\x18\b \x01(\x05R\x11replicationFactor\"\x83\x02\n" +
	"\x18InitiateTransferResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.transfer.v1.TransferStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\n" +
	"route_hops\x18\x05 \x03(\v2\x14.routing.v1.RouteHopR\trouteHops\"\x87\x01\n" +
	"\x10SendChunkRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x04 \x01(\tR\tchunkHash\"\xb5\x01\n" +
	"\x11SendChunkResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12'\n" +
	"\x0fchunks_received\x18\x02 \x01(\x05R\x0echunksReceived\x12!\n" +
	"\ftotal_chunks\x18\x03 \x01(\x05R\vtotalChunks\x123\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1b.transfer.v1.TransferStatusR\x06status\"\x82\x01\n" +
	"\x14ReceiveChunksRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vstart_chunk\x18\x02 \x01(\x05R\n" +
	"startChunk\x12(\n" +
	"\x10receiver_node_id\x18\x03 \x01(\tR\x0ereceiverNodeId\"\x99\x01\n" +
	"\tDataChunk\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x04 \x01(\tR\tchunkHash\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\";\n" +
	"\x18GetTransferStatusRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x87\x03\n" +
	"\x19GetTransferStatusResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.transfer.v1.TransferStatusR\x06status\x12-\n" +
	"\x12chunks_transferred\x18\x03 \x01(\x05R\x11chunksTransferred\x12!\n" +
	"\ftotal_chunks\x18\x04 \x01(\x05R\vtotalChunks\x12+\n" +
	"\x11bytes_transferred\x18\x05 \x01(\x03R\x10bytesTransferred\x12\x1f\n" +
	"\vtotal_bytes\x18\x06 \x01(\x03R\n" +
	"totalBytes\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x14ListTransfersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12@\n" +
	"\rfilter_status\x18\x02 \x01(\x0e2\x1b.transfer.v1.TransferStatusR\ffilterStatus\"P\n" +
	"\x15ListTransfersResponse\x127\n" +
	"\ttransfers\x18\x01 \x03(\v2\x19.transfer.v1.TransferInfoR\ttransfers\"\xe0\x02\n" +
	"\fTransferInfo\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12$\n" +
	"\x0esender_node_id\x18\x02 \x01(\tR\fsenderNodeId\x12(\n" +
	"\x10receiver_node_id\x18\x03 \x01(\tR\x0ereceiverNodeId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12(\n" +
	"\x10total_size_bytes\x18\x05 \x01(\x03R\x0etotalSizeBytes\x123\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1b.transfer.v1.TransferStatusR\x06status\x12)\n" +
	"\x10progress_percent\x18\a \x01(\x05R\x0fprogressPercent\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"P\n" +
	"\x15CancelTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"L\n" +
	"\x16CancelTransferResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xc9\x01\n" +
	"\x0eTransferStatus\x12\x1f\n" +
	"\x1bTRANSFER_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSFER_STATUS_PENDING\x10\x01\x12\x1f\n" +
	"\x1bTRANSFER_STATUS_IN_PROGRESS\x10\x02\x12\x1d\n" +
	"\x19TRANSFER_STATUS_COMPLETED\x10\x03\x12\x1a\n" +
	"\x16TRANSFER_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19TRANSFER_STATUS_CANCELLED\x10\x052\xa5\x04\n" +
	"\x0fTransferService\x12_\n" +
	"\x10InitiateTransfer\x12$.transfer.v1.InitiateTransferRequest\x1a%.transfer.v1.InitiateTransferResponse\x12L\n" +
	"\tSendChunk\x12\x1d.transfer.v1.SendChunkRequest\x1a\x1e.transfer.v1.SendChunkResponse(\x01\x12L\n" +
	"\rReceiveChunks\x12!.transfer.v1.ReceiveChunksRequest\x1a\x16.transfer.v1.DataChunk0\x01\x12b\n" +
	"\x11GetTransferStatus\x12%.transfer.v1.GetTransferStatusRequest\x1a&.transfer.v1.GetTransferStatusResponse\x12V\n" +
	"\rListTransfers\x12!.transfer.v1.ListTransfersRequest\x1a\".transfer.v1.ListTransfersResponse\x12Y\n" +
	"\x0eCancelTransfer\x12\".transfer.v1.CancelTransferRequest\x1a#.transfer.v1.CancelTransferResponseBBZ@github.com/saitddundar/vinctum-core/proto/transfer/v1;transferv1b\x06proto3"

var (
	file_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_transfer_v1_transfer_proto_rawDescData []byte
)

func file_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_v1_transfer_proto_rawDesc), len(file_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_transfer_v1_transfer_proto_rawDescData
}

var file_transfer_v1_transfer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_transfer_v1_transfer_proto_goTypes = []any{
	(TransferStatus)(0),               // 0: transfer.v1.TransferStatus
	(*InitiateTransferRequest)(nil),   // 1: transfer.v1.InitiateTransferRequest
	(*InitiateTransferResponse)(nil),  // 2: transfer.v1.InitiateTransferResponse
	(*SendChunkRequest)(nil),          // 3: transfer.v1.SendChunkRequest
	(*SendChunkResponse)(nil),         // 4: transfer.v1.SendChunkResponse
	(*ReceiveChunksRequest)(nil),      // 5: transfer.v1.ReceiveChunksRequest
	(*DataChunk)(nil),                 // 6: transfer.v1.DataChunk
	(*GetTransferStatusRequest)(nil),  // 7: transfer.v1.GetTransferStatusRequest
	(*GetTransferStatusResponse)(nil), // 8: transfer.v1.GetTransferStatusResponse
	(*ListTransfersRequest)(nil),      // 9: transfer.v1.ListTransfersRequest
	(*ListTransfersResponse)(nil),     // 10: transfer.v1.ListTransfersResponse
	(*TransferInfo)(nil),              // 11: transfer.v1.TransferInfo
	(*CancelTransferRequest)(nil),     // 12: transfer.v1.CancelTransferRequest
	(*CancelTransferResponse)(nil),    // 13: transfer.v1.CancelTransferResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
	(*v1.RouteHop)(nil),               // 15: routing.v1.RouteHop
}
var file_transfer_v1_transfer_proto_depIdxs = []int32{
	0,  // 0: transfer.v1.InitiateTransferResponse.status:type_name -> transfer.v1.TransferStatus
	14, // 1: transfer.v1.InitiateTransferResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: transfer.v1.InitiateTransferResponse.route_hops:type_name -> routing.v1.RouteHop
	0,  // 3: transfer.v1.SendChunkResponse.status:type_name -> transfer.v1.TransferStatus
	0,  // 4: transfer.v1.GetTransferStatusResponse.status:type_name -> transfer.v1.TransferStatus
	14, // 5: transfer.v1.GetTransferStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	14, // 6: transfer.v1.GetTransferStatusResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: transfer.v1.ListTransfersRequest.filter_status:type_name -> transfer.v1.TransferStatus
	11, // 8: transfer.v1.ListTransfersResponse.transfers:type_name -> transfer.v1.TransferInfo
	0,  // 9: transfer.v1.TransferInfo.status:type_name -> transfer.v1.TransferStatus
	14, // 10: transfer.v1.TransferInfo.created_at:type_name -> google.protobuf.Timestamp
	1,  // 11: transfer.v1.TransferService.InitiateTransfer:input_type -> transfer.v1.InitiateTransferRequest
	3,  // 12: transfer.v1.TransferService.SendChunk:input_type -> transfer.v1.SendChunkRequest
	5,  // 13: transfer.v1.TransferService.ReceiveChunks:input_type -> transfer.v1.ReceiveChunksRequest
	7,  // 14: transfer.v1.TransferService.GetTransferStatus:input_type -> transfer.v1.GetTransferStatusRequest
	9,  // 15: transfer.v1.TransferService.ListTransfers:input_type -> transfer.v1.ListTransfersRequest
	12, // 16: transfer.v1.TransferService.CancelTransfer:input_type -> transfer.v1.CancelTransferRequest
	2,  // 17: transfer.v1.TransferService.InitiateTransfer:output_type -> transfer.v1.InitiateTransferResponse
	4,  // 18: transfer.v1.TransferService.SendChunk:output_type -> transfer.v1.SendChunkResponse
	6,  // 19: transfer.v1.TransferService.ReceiveChunks:output_type -> transfer.v1.DataChunk
	8,  // 20: transfer.v1.TransferService.GetTransferStatus:output_type -> transfer.v1.GetTransferStatusResponse
	10, // 21: transfer.v1.TransferService.ListTransfers:output_type -> transfer.v1.ListTransfersResponse
	13, // 22: transfer.v1.TransferService.CancelTransfer:output_type -> transfer.v1.CancelTransferResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_transfer_v1_transfer_proto_init() }
func file_transfer_v1_transfer_proto_init() {
	if File_transfer_v1_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_v1_transfer_proto_rawDesc), len(file_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_transfer_v1_transfer_proto_depIdxs,
		EnumInfos:         file_transfer_v1_transfer_proto_enumTypes,
		MessageInfos:      file_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_transfer_v1_transfer_proto = out.File
	file_transfer_v1_transfer_proto_goTypes = nil
	file_transfer_v1_transfer_proto_depIdxs = nil
}
