// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: transfer/v1/transfer.proto

package transferv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransferService_InitiateTransfer_FullMethodName     = "/transfer.v1.TransferService/InitiateTransfer"
	TransferService_SendChunk_FullMethodName            = "/transfer.v1.TransferService/SendChunk"
	TransferService_ReceiveChunks_FullMethodName        = "/transfer.v1.TransferService/ReceiveChunks"
	TransferService_GetTransferStatus_FullMethodName    = "/transfer.v1.TransferService/GetTransferStatus"
	TransferService_ListTransfers_FullMethodName        = "/transfer.v1.TransferService/ListTransfers"
	TransferService_CancelTransfer_FullMethodName       = "/transfer.v1.TransferService/CancelTransfer"
	TransferService_WatchTransfers_FullMethodName       = "/transfer.v1.TransferService/WatchTransfers"
	TransferService_GetP2PConnectionInfo_FullMethodName = "/transfer.v1.TransferService/GetP2PConnectionInfo"
	TransferService_ConfirmP2PTransfer_FullMethodName   = "/transfer.v1.TransferService/ConfirmP2PTransfer"
)

// TransferServiceClient is the client API for TransferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransferServiceClient interface {
	// Initiates a new file/data transfer session.
	InitiateTransfer(ctx context.Context, in *InitiateTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error)
	// Streams encrypted data chunks from sender to the service (client streaming).
	SendChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendChunkRequest, SendChunkResponse], error)
	// Streams encrypted data chunks to the receiver (server streaming).
	ReceiveChunks(ctx context.Context, in *ReceiveChunksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error)
	// Queries the current status of a transfer.
	GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*GetTransferStatusResponse, error)
	// Lists transfers associated with a node.
	ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	// Cancels an in-progress transfer.
	CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error)
	// Streams transfer events (new/updated/completed) for a given node so
	// receivers can react to incoming transfers without polling.
	WatchTransfers(ctx context.Context, in *WatchTransfersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error)
	// Returns P2P connection info (peer ID, multiaddrs) for direct transfer.
	GetP2PConnectionInfo(ctx context.Context, in *GetP2PConnectionInfoRequest, opts ...grpc.CallOption) (*GetP2PConnectionInfoResponse, error)
	// Reports the result of a direct P2P transfer attempt.
	ConfirmP2PTransfer(ctx context.Context, in *ConfirmP2PTransferRequest, opts ...grpc.CallOption) (*ConfirmP2PTransferResponse, error)
}

type transferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransferServiceClient(cc grpc.ClientConnInterface) TransferServiceClient {
	return &transferServiceClient{cc}
}

func (c *transferServiceClient) InitiateTransfer(ctx context.Context, in *InitiateTransferRequest, opts ...grpc.CallOption) (*InitiateTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateTransferResponse)
	err := c.cc.Invoke(ctx, TransferService_InitiateTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) SendChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendChunkRequest, SendChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransferService_ServiceDesc.Streams[0], TransferService_SendChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendChunkRequest, SendChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_SendChunkClient = grpc.ClientStreamingClient[SendChunkRequest, SendChunkResponse]

func (c *transferServiceClient) ReceiveChunks(ctx context.Context, in *ReceiveChunksRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransferService_ServiceDesc.Streams[1], TransferService_ReceiveChunks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReceiveChunksRequest, DataChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_ReceiveChunksClient = grpc.ServerStreamingClient[DataChunk]

func (c *transferServiceClient) GetTransferStatus(ctx context.Context, in *GetTransferStatusRequest, opts ...grpc.CallOption) (*GetTransferStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransferStatusResponse)
	err := c.cc.Invoke(ctx, TransferService_GetTransferStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, TransferService_ListTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransferResponse)
	err := c.cc.Invoke(ctx, TransferService_CancelTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) WatchTransfers(ctx context.Context, in *WatchTransfersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TransferEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TransferService_ServiceDesc.Streams[2], TransferService_WatchTransfers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTransfersRequest, TransferEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_WatchTransfersClient = grpc.ServerStreamingClient[TransferEvent]

func (c *transferServiceClient) GetP2PConnectionInfo(ctx context.Context, in *GetP2PConnectionInfoRequest, opts ...grpc.CallOption) (*GetP2PConnectionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetP2PConnectionInfoResponse)
	err := c.cc.Invoke(ctx, TransferService_GetP2PConnectionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferServiceClient) ConfirmP2PTransfer(ctx context.Context, in *ConfirmP2PTransferRequest, opts ...grpc.CallOption) (*ConfirmP2PTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmP2PTransferResponse)
	err := c.cc.Invoke(ctx, TransferService_ConfirmP2PTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransferServiceServer is the server API for TransferService service.
// All implementations should embed UnimplementedTransferServiceServer
// for forward compatibility.
type TransferServiceServer interface {
	// Initiates a new file/data transfer session.
	InitiateTransfer(context.Context, *InitiateTransferRequest) (*InitiateTransferResponse, error)
	// Streams encrypted data chunks from sender to the service (client streaming).
	SendChunk(grpc.ClientStreamingServer[SendChunkRequest, SendChunkResponse]) error
	// Streams encrypted data chunks to the receiver (server streaming).
	ReceiveChunks(*ReceiveChunksRequest, grpc.ServerStreamingServer[DataChunk]) error
	// Queries the current status of a transfer.
	GetTransferStatus(context.Context, *GetTransferStatusRequest) (*GetTransferStatusResponse, error)
	// Lists transfers associated with a node.
	ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error)
	// Cancels an in-progress transfer.
	CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error)
	// Streams transfer events (new/updated/completed) for a given node so
	// receivers can react to incoming transfers without polling.
	WatchTransfers(*WatchTransfersRequest, grpc.ServerStreamingServer[TransferEvent]) error
	// Returns P2P connection info (peer ID, multiaddrs) for direct transfer.
	GetP2PConnectionInfo(context.Context, *GetP2PConnectionInfoRequest) (*GetP2PConnectionInfoResponse, error)
	// Reports the result of a direct P2P transfer attempt.
	ConfirmP2PTransfer(context.Context, *ConfirmP2PTransferRequest) (*ConfirmP2PTransferResponse, error)
}

// UnimplementedTransferServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransferServiceServer struct{}

func (UnimplementedTransferServiceServer) InitiateTransfer(context.Context, *InitiateTransferRequest) (*InitiateTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateTransfer not implemented")
}
func (UnimplementedTransferServiceServer) SendChunk(grpc.ClientStreamingServer[SendChunkRequest, SendChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method SendChunk not implemented")
}
func (UnimplementedTransferServiceServer) ReceiveChunks(*ReceiveChunksRequest, grpc.ServerStreamingServer[DataChunk]) error {
	return status.Error(codes.Unimplemented, "method ReceiveChunks not implemented")
}
func (UnimplementedTransferServiceServer) GetTransferStatus(context.Context, *GetTransferStatusRequest) (*GetTransferStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransferStatus not implemented")
}
func (UnimplementedTransferServiceServer) ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTransfers not implemented")
}
func (UnimplementedTransferServiceServer) CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTransfer not implemented")
}
func (UnimplementedTransferServiceServer) WatchTransfers(*WatchTransfersRequest, grpc.ServerStreamingServer[TransferEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTransfers not implemented")
}
func (UnimplementedTransferServiceServer) GetP2PConnectionInfo(context.Context, *GetP2PConnectionInfoRequest) (*GetP2PConnectionInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetP2PConnectionInfo not implemented")
}
func (UnimplementedTransferServiceServer) ConfirmP2PTransfer(context.Context, *ConfirmP2PTransferRequest) (*ConfirmP2PTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmP2PTransfer not implemented")
}
func (UnimplementedTransferServiceServer) testEmbeddedByValue() {}

// UnsafeTransferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransferServiceServer will
// result in compilation errors.
type UnsafeTransferServiceServer interface {
	mustEmbedUnimplementedTransferServiceServer()
}

func RegisterTransferServiceServer(s grpc.ServiceRegistrar, srv TransferServiceServer) {
	// If the following call panics, it indicates UnimplementedTransferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransferService_ServiceDesc, srv)
}

func _TransferService_InitiateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).InitiateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_InitiateTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).InitiateTransfer(ctx, req.(*InitiateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_SendChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TransferServiceServer).SendChunk(&grpc.GenericServerStream[SendChunkRequest, SendChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_SendChunkServer = grpc.ClientStreamingServer[SendChunkRequest, SendChunkResponse]

func _TransferService_ReceiveChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveChunksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServiceServer).ReceiveChunks(m, &grpc.GenericServerStream[ReceiveChunksRequest, DataChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_ReceiveChunksServer = grpc.ServerStreamingServer[DataChunk]

func _TransferService_GetTransferStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransferStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_GetTransferStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetTransferStatus(ctx, req.(*GetTransferStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_ListTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).ListTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_ListTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).ListTransfers(ctx, req.(*ListTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_CancelTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).CancelTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_CancelTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).CancelTransfer(ctx, req.(*CancelTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_WatchTransfers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTransfersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TransferServiceServer).WatchTransfers(m, &grpc.GenericServerStream[WatchTransfersRequest, TransferEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TransferService_WatchTransfersServer = grpc.ServerStreamingServer[TransferEvent]

func _TransferService_GetP2PConnectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetP2PConnectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).GetP2PConnectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_GetP2PConnectionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).GetP2PConnectionInfo(ctx, req.(*GetP2PConnectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransferService_ConfirmP2PTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmP2PTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServiceServer).ConfirmP2PTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransferService_ConfirmP2PTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServiceServer).ConfirmP2PTransfer(ctx, req.(*ConfirmP2PTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransferService_ServiceDesc is the grpc.ServiceDesc for TransferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transfer.v1.TransferService",
	HandlerType: (*TransferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitiateTransfer",
			Handler:    _TransferService_InitiateTransfer_Handler,
		},
		{
			MethodName: "GetTransferStatus",
			Handler:    _TransferService_GetTransferStatus_Handler,
		},
		{
			MethodName: "ListTransfers",
			Handler:    _TransferService_ListTransfers_Handler,
		},
		{
			MethodName: "CancelTransfer",
			Handler:    _TransferService_CancelTransfer_Handler,
		},
		{
			MethodName: "GetP2PConnectionInfo",
			Handler:    _TransferService_GetP2PConnectionInfo_Handler,
		},
		{
			MethodName: "ConfirmP2PTransfer",
			Handler:    _TransferService_ConfirmP2PTransfer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendChunk",
			Handler:       _TransferService_SendChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveChunks",
			Handler:       _TransferService_ReceiveChunks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchTransfers",
			Handler:       _TransferService_WatchTransfers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "transfer/v1/transfer.proto",
}
