// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: routing/v1/routing.proto

package routingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutingService_FindRoute_FullMethodName        = "/routing.v1.RoutingService/FindRoute"
	RoutingService_UpdateRouteTable_FullMethodName = "/routing.v1.RoutingService/UpdateRouteTable"
	RoutingService_GetRouteTable_FullMethodName    = "/routing.v1.RoutingService/GetRouteTable"
	RoutingService_ListRelays_FullMethodName       = "/routing.v1.RoutingService/ListRelays"
	RoutingService_RegisterRelay_FullMethodName    = "/routing.v1.RoutingService/RegisterRelay"
)

// RoutingServiceClient is the client API for RoutingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoutingServiceClient interface {
	// Computes the best route to the target node.
	FindRoute(ctx context.Context, in *FindRouteRequest, opts ...grpc.CallOption) (*FindRouteResponse, error)
	// Updates a node's routing table entries.
	UpdateRouteTable(ctx context.Context, in *UpdateRouteTableRequest, opts ...grpc.CallOption) (*UpdateRouteTableResponse, error)
	// Retrieves the full routing table for a given node.
	GetRouteTable(ctx context.Context, in *GetRouteTableRequest, opts ...grpc.CallOption) (*GetRouteTableResponse, error)
	// Lists available relay nodes ordered by latency.
	ListRelays(ctx context.Context, in *ListRelaysRequest, opts ...grpc.CallOption) (*ListRelaysResponse, error)
	// Registers or updates a relay node.
	RegisterRelay(ctx context.Context, in *RegisterRelayRequest, opts ...grpc.CallOption) (*RegisterRelayResponse, error)
}

type routingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutingServiceClient(cc grpc.ClientConnInterface) RoutingServiceClient {
	return &routingServiceClient{cc}
}

func (c *routingServiceClient) FindRoute(ctx context.Context, in *FindRouteRequest, opts ...grpc.CallOption) (*FindRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRouteResponse)
	err := c.cc.Invoke(ctx, RoutingService_FindRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) UpdateRouteTable(ctx context.Context, in *UpdateRouteTableRequest, opts ...grpc.CallOption) (*UpdateRouteTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRouteTableResponse)
	err := c.cc.Invoke(ctx, RoutingService_UpdateRouteTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) GetRouteTable(ctx context.Context, in *GetRouteTableRequest, opts ...grpc.CallOption) (*GetRouteTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteTableResponse)
	err := c.cc.Invoke(ctx, RoutingService_GetRouteTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) ListRelays(ctx context.Context, in *ListRelaysRequest, opts ...grpc.CallOption) (*ListRelaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRelaysResponse)
	err := c.cc.Invoke(ctx, RoutingService_ListRelays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routingServiceClient) RegisterRelay(ctx context.Context, in *RegisterRelayRequest, opts ...grpc.CallOption) (*RegisterRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterRelayResponse)
	err := c.cc.Invoke(ctx, RoutingService_RegisterRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutingServiceServer is the server API for RoutingService service.
// All implementations should embed UnimplementedRoutingServiceServer
// for forward compatibility.
type RoutingServiceServer interface {
	// Computes the best route to the target node.
	FindRoute(context.Context, *FindRouteRequest) (*FindRouteResponse, error)
	// Updates a node's routing table entries.
	UpdateRouteTable(context.Context, *UpdateRouteTableRequest) (*UpdateRouteTableResponse, error)
	// Retrieves the full routing table for a given node.
	GetRouteTable(context.Context, *GetRouteTableRequest) (*GetRouteTableResponse, error)
	// Lists available relay nodes ordered by latency.
	ListRelays(context.Context, *ListRelaysRequest) (*ListRelaysResponse, error)
	// Registers or updates a relay node.
	RegisterRelay(context.Context, *RegisterRelayRequest) (*RegisterRelayResponse, error)
}

// UnimplementedRoutingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutingServiceServer struct{}

func (UnimplementedRoutingServiceServer) FindRoute(context.Context, *FindRouteRequest) (*FindRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindRoute not implemented")
}
func (UnimplementedRoutingServiceServer) UpdateRouteTable(context.Context, *UpdateRouteTableRequest) (*UpdateRouteTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRouteTable not implemented")
}
func (UnimplementedRoutingServiceServer) GetRouteTable(context.Context, *GetRouteTableRequest) (*GetRouteTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteTable not implemented")
}
func (UnimplementedRoutingServiceServer) ListRelays(context.Context, *ListRelaysRequest) (*ListRelaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRelays not implemented")
}
func (UnimplementedRoutingServiceServer) RegisterRelay(context.Context, *RegisterRelayRequest) (*RegisterRelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterRelay not implemented")
}
func (UnimplementedRoutingServiceServer) testEmbeddedByValue() {}

// UnsafeRoutingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutingServiceServer will
// result in compilation errors.
type UnsafeRoutingServiceServer interface {
	mustEmbedUnimplementedRoutingServiceServer()
}

func RegisterRoutingServiceServer(s grpc.ServiceRegistrar, srv RoutingServiceServer) {
	// If the following call panics, it indicates UnimplementedRoutingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutingService_ServiceDesc, srv)
}

func _RoutingService_FindRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).FindRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_FindRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).FindRoute(ctx, req.(*FindRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_UpdateRouteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRouteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).UpdateRouteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_UpdateRouteTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).UpdateRouteTable(ctx, req.(*UpdateRouteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_GetRouteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).GetRouteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_GetRouteTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).GetRouteTable(ctx, req.(*GetRouteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_ListRelays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRelaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).ListRelays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_ListRelays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).ListRelays(ctx, req.(*ListRelaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RoutingService_RegisterRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutingServiceServer).RegisterRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutingService_RegisterRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutingServiceServer).RegisterRelay(ctx, req.(*RegisterRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutingService_ServiceDesc is the grpc.ServiceDesc for RoutingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routing.v1.RoutingService",
	HandlerType: (*RoutingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindRoute",
			Handler:    _RoutingService_FindRoute_Handler,
		},
		{
			MethodName: "UpdateRouteTable",
			Handler:    _RoutingService_UpdateRouteTable_Handler,
		},
		{
			MethodName: "GetRouteTable",
			Handler:    _RoutingService_GetRouteTable_Handler,
		},
		{
			MethodName: "ListRelays",
			Handler:    _RoutingService_ListRelays_Handler,
		},
		{
			MethodName: "RegisterRelay",
			Handler:    _RoutingService_RegisterRelay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "routing/v1/routing.proto",
}
