// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: routing/v1/routing.proto

package routingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindRouteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceNodeId   string                 `protobuf:"bytes,1,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId   string                 `protobuf:"bytes,2,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	MaxHops        int32                  `protobuf:"varint,3,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`                       // Maximum hop count (default: 5)
	ExcludeNodeIds []string               `protobuf:"bytes,4,rep,name=exclude_node_ids,json=excludeNodeIds,proto3" json:"exclude_node_ids,omitempty"` // Nodes to skip (for rerouting around failures)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindRouteRequest) Reset() {
	*x = FindRouteRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteRequest) ProtoMessage() {}

func (x *FindRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteRequest.ProtoReflect.Descriptor instead.
func (*FindRouteRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *FindRouteRequest) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *FindRouteRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *FindRouteRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *FindRouteRequest) GetExcludeNodeIds() []string {
	if x != nil {
		return x.ExcludeNodeIds
	}
	return nil
}

type FindRouteResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Hops               []*RouteHop            `protobuf:"bytes,1,rep,name=hops,proto3" json:"hops,omitempty"`
	TotalHops          int32                  `protobuf:"varint,2,opt,name=total_hops,json=totalHops,proto3" json:"total_hops,omitempty"`
	EstimatedLatencyMs int64                  `protobuf:"varint,3,opt,name=estimated_latency_ms,json=estimatedLatencyMs,proto3" json:"estimated_latency_ms,omitempty"` // Estimated end-to-end latency (ms)
	DirectPossible     bool                   `protobuf:"varint,4,opt,name=direct_possible,json=directPossible,proto3" json:"direct_possible,omitempty"`               // Whether a direct connection is possible
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FindRouteResponse) Reset() {
	*x = FindRouteResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRouteResponse) ProtoMessage() {}

func (x *FindRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRouteResponse.ProtoReflect.Descriptor instead.
func (*FindRouteResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *FindRouteResponse) GetHops() []*RouteHop {
	if x != nil {
		return x.Hops
	}
	return nil
}

func (x *FindRouteResponse) GetTotalHops() int32 {
	if x != nil {
		return x.TotalHops
	}
	return 0
}

func (x *FindRouteResponse) GetEstimatedLatencyMs() int64 {
	if x != nil {
		return x.EstimatedLatencyMs
	}
	return 0
}

func (x *FindRouteResponse) GetDirectPossible() bool {
	if x != nil {
		return x.DirectPossible
	}
	return false
}

type RouteHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` // multiaddr
	IsRelay       bool                   `protobuf:"varint,3,opt,name=is_relay,json=isRelay,proto3" json:"is_relay,omitempty"`
	HopIndex      int32                  `protobuf:"varint,4,opt,name=hop_index,json=hopIndex,proto3" json:"hop_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteHop) Reset() {
	*x = RouteHop{}
	mi := &file_routing_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteHop) ProtoMessage() {}

func (x *RouteHop) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteHop.ProtoReflect.Descriptor instead.
func (*RouteHop) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *RouteHop) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteHop) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RouteHop) GetIsRelay() bool {
	if x != nil {
		return x.IsRelay
	}
	return false
}

func (x *RouteHop) GetHopIndex() int32 {
	if x != nil {
		return x.HopIndex
	}
	return 0
}

type UpdateRouteTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Entries       []*RouteEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteTableRequest) Reset() {
	*x = UpdateRouteTableRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteTableRequest) ProtoMessage() {}

func (x *UpdateRouteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteTableRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteTableRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRouteTableRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateRouteTableRequest) GetEntries() []*RouteEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UpdateRouteTableResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EntriesUpdated int32                  `protobuf:"varint,2,opt,name=entries_updated,json=entriesUpdated,proto3" json:"entries_updated,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRouteTableResponse) Reset() {
	*x = UpdateRouteTableResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteTableResponse) ProtoMessage() {}

func (x *UpdateRouteTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteTableResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteTableResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRouteTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRouteTableResponse) GetEntriesUpdated() int32 {
	if x != nil {
		return x.EntriesUpdated
	}
	return 0
}

func (x *UpdateRouteTableResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RouteEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	NextHopId     string                 `protobuf:"bytes,2,opt,name=next_hop_id,json=nextHopId,proto3" json:"next_hop_id,omitempty"`
	Metric        int32                  `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"` // Cost metric (lower = better)
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEntry) Reset() {
	*x = RouteEntry{}
	mi := &file_routing_v1_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEntry) ProtoMessage() {}

func (x *RouteEntry) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEntry.ProtoReflect.Descriptor instead.
func (*RouteEntry) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{5}
}

func (x *RouteEntry) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *RouteEntry) GetNextHopId() string {
	if x != nil {
		return x.NextHopId
	}
	return ""
}

func (x *RouteEntry) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *RouteEntry) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type GetRouteTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteTableRequest) Reset() {
	*x = GetRouteTableRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteTableRequest) ProtoMessage() {}

func (x *GetRouteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteTableRequest.ProtoReflect.Descriptor instead.
func (*GetRouteTableRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{6}
}

func (x *GetRouteTableRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetRouteTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Entries       []*RouteEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteTableResponse) Reset() {
	*x = GetRouteTableResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteTableResponse) ProtoMessage() {}

func (x *GetRouteTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteTableResponse.ProtoReflect.Descriptor instead.
func (*GetRouteTableResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteTableResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetRouteTableResponse) GetEntries() []*RouteEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetRouteTableResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type ListRelaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelaysRequest) Reset() {
	*x = ListRelaysRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelaysRequest) ProtoMessage() {}

func (x *ListRelaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelaysRequest.ProtoReflect.Descriptor instead.
func (*ListRelaysRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{8}
}

func (x *ListRelaysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRelaysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relays        []*RelayInfo           `protobuf:"bytes,1,rep,name=relays,proto3" json:"relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelaysResponse) Reset() {
	*x = ListRelaysResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelaysResponse) ProtoMessage() {}

func (x *ListRelaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelaysResponse.ProtoReflect.Descriptor instead.
func (*ListRelaysResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{9}
}

func (x *ListRelaysResponse) GetRelays() []*RelayInfo {
	if x != nil {
		return x.Relays
	}
	return nil
}

type RelayInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address        string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	ActiveCircuits int32                  `protobuf:"varint,3,opt,name=active_circuits,json=activeCircuits,proto3" json:"active_circuits,omitempty"`
	MaxCircuits    int32                  `protobuf:"varint,4,opt,name=max_circuits,json=maxCircuits,proto3" json:"max_circuits,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayInfo) Reset() {
	*x = RelayInfo{}
	mi := &file_routing_v1_routing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfo) ProtoMessage() {}

func (x *RelayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfo.ProtoReflect.Descriptor instead.
func (*RelayInfo) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{10}
}

func (x *RelayInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RelayInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RelayInfo) GetActiveCircuits() int32 {
	if x != nil {
		return x.ActiveCircuits
	}
	return 0
}

func (x *RelayInfo) GetMaxCircuits() int32 {
	if x != nil {
		return x.MaxCircuits
	}
	return 0
}

func (x *RelayInfo) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RelayInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

type RegisterRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	MaxCircuits   int32                  `protobuf:"varint,3,opt,name=max_circuits,json=maxCircuits,proto3" json:"max_circuits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRelayRequest) Reset() {
	*x = RegisterRelayRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRelayRequest) ProtoMessage() {}

func (x *RegisterRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRelayRequest.ProtoReflect.Descriptor instead.
func (*RegisterRelayRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRelayRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRelayRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRelayRequest) GetMaxCircuits() int32 {
	if x != nil {
		return x.MaxCircuits
	}
	return 0
}

type RegisterRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RegisteredAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRelayResponse) Reset() {
	*x = RegisterRelayResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRelayResponse) ProtoMessage() {}

func (x *RegisterRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRelayResponse.ProtoReflect.Descriptor instead.
func (*RegisterRelayResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterRelayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterRelayResponse) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

var File_routing_v1_routing_proto protoreflect.FileDescriptor

const file_routing_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\x18routing/v1/routing.proto\x12\n" +
	"routing.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x10FindRouteRequest\x12$\n" +
	"\x0esource_node_id\x18\x01 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x02 \x01(\tR\ftargetNodeId\x12\x19\n" +
	"\bmax_hops\x18\x03 \x01(\x05R\amaxHops\x12(\n" +
	"\x10exclude_node_ids\x18\x04 \x03(\tR\x0eexcludeNodeIds\"\xb7\x01\n" +
	"\x11FindRouteResponse\x12(\n" +
	"\x04hops\x18\x01 \x03(\v2\x14.routing.v1.RouteHopR\x04hops\x12\x1d\n" +
	"\n" +
	"total_hops\x18\x02 \x01(\x05R\ttotalHops\x120\n" +
	"\x14estimated_latency_ms\x18\x03 \x01(\x03R\x12estimatedLatencyMs\x12'\n" +
	"\x0fdirect_possible\x18\x04 \x01(\bR\x0edirectPossible\"u\n" +
	"\bRouteHop\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x19\n" +
	"\bis_relay\x18\x03 \x01(\bR\aisRelay\x12\x1b\n" +
	"\thop_index\x18\x04 \x01(\x05R\bhopIndex\"d\n" +
	"\x17UpdateRouteTableRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\aentries\x18\x02 \x03(\v2\x16.routing.v1.RouteEntryR\aentries\"\x98\x01\n" +
	"\x18UpdateRouteTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fentries_updated\x18\x02 \x01(\x05R\x0eentriesUpdated\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x89\x01\n" +
	"\n" +
	"RouteEntry\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x1e\n" +
	"\vnext_hop_id\x18\x02 \x01(\tR\tnextHopId\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\x05R\x06metric\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"/\n" +
	"\x14GetRouteTableRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xa1\x01\n" +
	"\x15GetRouteTableResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\aentries\x18\x02 \x03(\v2\x16.routing.v1.RouteEntryR\aentries\x12=\n" +
	"\flast_updated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\")\n" +
	"\x11ListRelaysRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"C\n" +
	"\x12ListRelaysResponse\x12-\n" +
	"\x06relays\x18\x01 \x03(\v2\x15.routing.v1.RelayInfoR\x06relays\"\xe2\x01\n" +
	"\tRelayInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12'\n" +
	"\x0factive_circuits\x18\x03 \x01(\x05R\x0eactiveCircuits\x12!\n" +
	"\fmax_circuits\x18\x04 \x01(\x05R\vmaxCircuits\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x03R\tlatencyMs\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\"l\n" +
	"\x14RegisterRelayRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fmax_circuits\x18\x03 \x01(\x05R\vmaxCircuits\"r\n" +
	"\x15RegisterRelayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12?\n" +
	"\rregistered_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt2\xb2\x03\n" +
	"\x0eRoutingService\x12H\n" +
	"\tFindRoute\x12\x1c.routing.v1.FindRouteRequest\x1a\x1d.routing.v1.FindRouteResponse\x12]\n" +
	"\x10UpdateRouteTable\x12#.routing.v1.UpdateRouteTableRequest\x1a$.routing.v1.UpdateRouteTableResponse\x12T\n" +
	"\rGetRouteTable\x12 .routing.v1.GetRouteTableRequest\x1a!.routing.v1.GetRouteTableResponse\x12K\n" +
	"\n" +
	"ListRelays\x12\x1d.routing.v1.ListRelaysRequest\x1a\x1e.routing.v1.ListRelaysResponse\x12T\n" +
	"\rRegisterRelay\x12 .routing.v1.RegisterRelayRequest\x1a!.routing.v1.RegisterRelayResponseB@Z>github.com/saitddundar/vinctum-core/proto/routing/v1;routingv1b\x06proto3"

var (
	file_routing_v1_routing_proto_rawDescOnce sync.Once
	file_routing_v1_routing_proto_rawDescData []byte
)

func file_routing_v1_routing_proto_rawDescGZIP() []byte {
	file_routing_v1_routing_proto_rawDescOnce.Do(func() {
		file_routing_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_v1_routing_proto_rawDesc), len(file_routing_v1_routing_proto_rawDesc)))
	})
	return file_routing_v1_routing_proto_rawDescData
}

var file_routing_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_routing_v1_routing_proto_goTypes = []any{
	(*FindRouteRequest)(nil),         // 0: routing.v1.FindRouteRequest
	(*FindRouteResponse)(nil),        // 1: routing.v1.FindRouteResponse
	(*RouteHop)(nil),                 // 2: routing.v1.RouteHop
	(*UpdateRouteTableRequest)(nil),  // 3: routing.v1.UpdateRouteTableRequest
	(*UpdateRouteTableResponse)(nil), // 4: routing.v1.UpdateRouteTableResponse
	(*RouteEntry)(nil),               // 5: routing.v1.RouteEntry
	(*GetRouteTableRequest)(nil),     // 6: routing.v1.GetRouteTableRequest
	(*GetRouteTableResponse)(nil),    // 7: routing.v1.GetRouteTableResponse
	(*ListRelaysRequest)(nil),        // 8: routing.v1.ListRelaysRequest
	(*ListRelaysResponse)(nil),       // 9: routing.v1.ListRelaysResponse
	(*RelayInfo)(nil),                // 10: routing.v1.RelayInfo
	(*RegisterRelayRequest)(nil),     // 11: routing.v1.RegisterRelayRequest
	(*RegisterRelayResponse)(nil),    // 12: routing.v1.RegisterRelayResponse
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_routing_v1_routing_proto_depIdxs = []int32{
	2,  // 0: routing.v1.FindRouteResponse.hops:type_name -> routing.v1.RouteHop
	5,  // 1: routing.v1.UpdateRouteTableRequest.entries:type_name -> routing.v1.RouteEntry
	13, // 2: routing.v1.UpdateRouteTableResponse.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: routing.v1.GetRouteTableResponse.entries:type_name -> routing.v1.RouteEntry
	13, // 4: routing.v1.GetRouteTableResponse.last_updated:type_name -> google.protobuf.Timestamp
	10, // 5: routing.v1.ListRelaysResponse.relays:type_name -> routing.v1.RelayInfo
	13, // 6: routing.v1.RelayInfo.last_seen:type_name -> google.protobuf.Timestamp
	13, // 7: routing.v1.RegisterRelayResponse.registered_at:type_name -> google.protobuf.Timestamp
	0,  // 8: routing.v1.RoutingService.FindRoute:input_type -> routing.v1.FindRouteRequest
	3,  // 9: routing.v1.RoutingService.UpdateRouteTable:input_type -> routing.v1.UpdateRouteTableRequest
	6,  // 10: routing.v1.RoutingService.GetRouteTable:input_type -> routing.v1.GetRouteTableRequest
	8,  // 11: routing.v1.RoutingService.ListRelays:input_type -> routing.v1.ListRelaysRequest
	11, // 12: routing.v1.RoutingService.RegisterRelay:input_type -> routing.v1.RegisterRelayRequest
	1,  // 13: routing.v1.RoutingService.FindRoute:output_type -> routing.v1.FindRouteResponse
	4,  // 14: routing.v1.RoutingService.UpdateRouteTable:output_type -> routing.v1.UpdateRouteTableResponse
	7,  // 15: routing.v1.RoutingService.GetRouteTable:output_type -> routing.v1.GetRouteTableResponse
	9,  // 16: routing.v1.RoutingService.ListRelays:output_type -> routing.v1.ListRelaysResponse
	12, // 17: routing.v1.RoutingService.RegisterRelay:output_type -> routing.v1.RegisterRelayResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_routing_v1_routing_proto_init() }
func file_routing_v1_routing_proto_init() {
	if File_routing_v1_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_v1_routing_proto_rawDesc), len(file_routing_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_v1_routing_proto_goTypes,
		DependencyIndexes: file_routing_v1_routing_proto_depIdxs,
		MessageInfos:      file_routing_v1_routing_proto_msgTypes,
	}.Build()
	File_routing_v1_routing_proto = out.File
	file_routing_v1_routing_proto_goTypes = nil
	file_routing_v1_routing_proto_depIdxs = nil
}
