// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type Relay struct {
	NodeID         string    `json:"node_id"`
	Address        string    `json:"address"`
	MaxCircuits    int32     `json:"max_circuits"`
	ActiveCircuits int32     `json:"active_circuits"`
	LatencyMs      int64     `json:"latency_ms"`
	LastSeen       time.Time `json:"last_seen"`
}

type Route struct {
	ID           int32     `json:"id"`
	NodeID       string    `json:"node_id"`
	TargetNodeID string    `json:"target_node_id"`
	NextHopID    string    `json:"next_hop_id"`
	Metric       int32     `json:"metric"`
	LatencyMs    int64     `json:"latency_ms"`
	UpdatedAt    time.Time `json:"updated_at"`
}
