// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const deleteRoute = `-- name: DeleteRoute :exec
DELETE FROM routes WHERE node_id = $1 AND target_node_id = $2
`

type DeleteRouteParams struct {
	NodeID       string `json:"node_id"`
	TargetNodeID string `json:"target_node_id"`
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) error {
	_, err := q.db.Exec(ctx, deleteRoute, arg.NodeID, arg.TargetNodeID)
	return err
}

const findRoute = `-- name: FindRoute :one
SELECT id, node_id, target_node_id, next_hop_id, metric, latency_ms, updated_at FROM routes WHERE node_id = $1 AND target_node_id = $2
`

type FindRouteParams struct {
	NodeID       string `json:"node_id"`
	TargetNodeID string `json:"target_node_id"`
}

func (q *Queries) FindRoute(ctx context.Context, arg FindRouteParams) (Route, error) {
	row := q.db.QueryRow(ctx, findRoute, arg.NodeID, arg.TargetNodeID)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.TargetNodeID,
		&i.NextHopID,
		&i.Metric,
		&i.LatencyMs,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelay = `-- name: GetRelay :one
SELECT node_id, address, max_circuits, active_circuits, latency_ms, last_seen FROM relays WHERE node_id = $1
`

func (q *Queries) GetRelay(ctx context.Context, nodeID string) (Relay, error) {
	row := q.db.QueryRow(ctx, getRelay, nodeID)
	var i Relay
	err := row.Scan(
		&i.NodeID,
		&i.Address,
		&i.MaxCircuits,
		&i.ActiveCircuits,
		&i.LatencyMs,
		&i.LastSeen,
	)
	return i, err
}

const getRoutesByNodeID = `-- name: GetRoutesByNodeID :many
SELECT id, node_id, target_node_id, next_hop_id, metric, latency_ms, updated_at FROM routes WHERE node_id = $1 ORDER BY metric ASC
`

func (q *Queries) GetRoutesByNodeID(ctx context.Context, nodeID string) ([]Route, error) {
	rows, err := q.db.Query(ctx, getRoutesByNodeID, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Route
	for rows.Next() {
		var i Route
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.TargetNodeID,
			&i.NextHopID,
			&i.Metric,
			&i.LatencyMs,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelays = `-- name: ListRelays :many
SELECT node_id, address, max_circuits, active_circuits, latency_ms, last_seen FROM relays ORDER BY latency_ms ASC LIMIT $1
`

func (q *Queries) ListRelays(ctx context.Context, limit int32) ([]Relay, error) {
	rows, err := q.db.Query(ctx, listRelays, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relay
	for rows.Next() {
		var i Relay
		if err := rows.Scan(
			&i.NodeID,
			&i.Address,
			&i.MaxCircuits,
			&i.ActiveCircuits,
			&i.LatencyMs,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelay = `-- name: UpsertRelay :exec
INSERT INTO relays (node_id, address, max_circuits, active_circuits, latency_ms, last_seen)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (node_id) DO UPDATE
SET address         = EXCLUDED.address,
    max_circuits    = EXCLUDED.max_circuits,
    active_circuits = EXCLUDED.active_circuits,
    latency_ms      = EXCLUDED.latency_ms,
    last_seen       = NOW()
`

type UpsertRelayParams struct {
	NodeID         string `json:"node_id"`
	Address        string `json:"address"`
	MaxCircuits    int32  `json:"max_circuits"`
	ActiveCircuits int32  `json:"active_circuits"`
	LatencyMs      int64  `json:"latency_ms"`
}

func (q *Queries) UpsertRelay(ctx context.Context, arg UpsertRelayParams) error {
	_, err := q.db.Exec(ctx, upsertRelay,
		arg.NodeID,
		arg.Address,
		arg.MaxCircuits,
		arg.ActiveCircuits,
		arg.LatencyMs,
	)
	return err
}

const upsertRoute = `-- name: UpsertRoute :exec
INSERT INTO routes (node_id, target_node_id, next_hop_id, metric, latency_ms, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (node_id, target_node_id) DO UPDATE
SET next_hop_id = EXCLUDED.next_hop_id,
    metric      = EXCLUDED.metric,
    latency_ms  = EXCLUDED.latency_ms,
    updated_at  = NOW()
`

type UpsertRouteParams struct {
	NodeID       string `json:"node_id"`
	TargetNodeID string `json:"target_node_id"`
	NextHopID    string `json:"next_hop_id"`
	Metric       int32  `json:"metric"`
	LatencyMs    int64  `json:"latency_ms"`
}

func (q *Queries) UpsertRoute(ctx context.Context, arg UpsertRouteParams) error {
	_, err := q.db.Exec(ctx, upsertRoute,
		arg.NodeID,
		arg.TargetNodeID,
		arg.NextHopID,
		arg.Metric,
		arg.LatencyMs,
	)
	return err
}
