// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	DeleteRoute(ctx context.Context, arg DeleteRouteParams) error
	FindRoute(ctx context.Context, arg FindRouteParams) (Route, error)
	GetRelay(ctx context.Context, nodeID string) (Relay, error)
	GetRoutesByNodeID(ctx context.Context, nodeID string) ([]Route, error)
	ListRelays(ctx context.Context, limit int32) ([]Relay, error)
	UpsertRelay(ctx context.Context, arg UpsertRelayParams) error
	UpsertRoute(ctx context.Context, arg UpsertRouteParams) error
}

var _ Querier = (*Queries)(nil)
