FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/discovery ./cmd/discovery/...

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /go/bin/discovery /discovery

EXPOSE 50052
EXPOSE 4001/tcp
EXPOSE 4001/udp
EXPOSE 51052

ENTRYPOINT ["/discovery"]
