FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /go/bin/gateway ./cmd/gateway/...

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /go/bin/gateway /gateway

EXPOSE 8080

ENTRYPOINT ["/gateway"]
