// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const completeTransfer = `-- name: CompleteTransfer :exec
UPDATE transfers SET status = 3, chunks_done = total_chunks, updated_at = NOW() WHERE transfer_id = $1
`

func (q *Queries) CompleteTransfer(ctx context.Context, transferID string) error {
	_, err := q.db.Exec(ctx, completeTransfer, transferID)
	return err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, status, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey
`

type CreateTransferParams struct {
	TransferID            string `json:"transfer_id"`
	SenderNodeID          string `json:"sender_node_id"`
	ReceiverNodeID        string `json:"receiver_node_id"`
	Filename              string `json:"filename"`
	TotalSizeBytes        int64  `json:"total_size_bytes"`
	ContentHash           string `json:"content_hash"`
	ChunkSizeBytes        int32  `json:"chunk_size_bytes"`
	TotalChunks           int32  `json:"total_chunks"`
	Status                int32  `json:"status"`
	EncryptionKey         string `json:"encryption_key"`
	RouteHops             []byte `json:"route_hops"`
	ReplicationFactor     int32  `json:"replication_factor"`
	SenderEphemeralPubkey []byte `json:"sender_ephemeral_pubkey"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.TransferID,
		arg.SenderNodeID,
		arg.ReceiverNodeID,
		arg.Filename,
		arg.TotalSizeBytes,
		arg.ContentHash,
		arg.ChunkSizeBytes,
		arg.TotalChunks,
		arg.Status,
		arg.EncryptionKey,
		arg.RouteHops,
		arg.ReplicationFactor,
		arg.SenderEphemeralPubkey,
	)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.SenderNodeID,
		&i.ReceiverNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.ChunksDone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionKey,
		&i.RouteHops,
		&i.ReplicationFactor,
		&i.SenderEphemeralPubkey,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey FROM transfers WHERE transfer_id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, transferID string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, transferID)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.SenderNodeID,
		&i.ReceiverNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.ChunksDone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionKey,
		&i.RouteHops,
		&i.ReplicationFactor,
		&i.SenderEphemeralPubkey,
	)
	return i, err
}

const listTransfersByNode = `-- name: ListTransfersByNode :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey FROM transfers WHERE sender_node_id = $1 OR receiver_node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTransfersByNode(ctx context.Context, senderNodeID string) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByNode, senderNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByStatus = `-- name: ListTransfersByStatus :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey FROM transfers WHERE (sender_node_id = $1 OR receiver_node_id = $1) AND status = $2 ORDER BY created_at DESC
`

type ListTransfersByStatusParams struct {
	SenderNodeID string `json:"sender_node_id"`
	Status       int32  `json:"status"`
}

func (q *Queries) ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByStatus, arg.SenderNodeID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRouteHops = `-- name: UpdateRouteHops :exec
UPDATE transfers SET route_hops = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateRouteHopsParams struct {
	TransferID string `json:"transfer_id"`
	RouteHops  []byte `json:"route_hops"`
}

func (q *Queries) UpdateRouteHops(ctx context.Context, arg UpdateRouteHopsParams) error {
	_, err := q.db.Exec(ctx, updateRouteHops, arg.TransferID, arg.RouteHops)
	return err
}

const updateTransferProgress = `-- name: UpdateTransferProgress :exec
UPDATE transfers SET chunks_done = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateTransferProgressParams struct {
	TransferID string `json:"transfer_id"`
	ChunksDone int32  `json:"chunks_done"`
}

func (q *Queries) UpdateTransferProgress(ctx context.Context, arg UpdateTransferProgressParams) error {
	_, err := q.db.Exec(ctx, updateTransferProgress, arg.TransferID, arg.ChunksDone)
	return err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers SET status = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateTransferStatusParams struct {
	TransferID string `json:"transfer_id"`
	Status     int32  `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.TransferID, arg.Status)
	return err
}
