// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AdminListTransfers(ctx context.Context, arg AdminListTransfersParams) ([]Transfer, error)
	CompleteTransfer(ctx context.Context, transferID string) error
	ConfirmP2PTransfer(ctx context.Context, arg ConfirmP2PTransferParams) error
	// ─── Platform Stats ────────────────────────────────
	CountTransfers(ctx context.Context) (int64, error)
	// ─── Group Transfers ────────────────────────────────────
	CreateGroupTransfer(ctx context.Context, arg CreateGroupTransferParams) (GroupTransfer, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	GetGroupTransfer(ctx context.Context, id string) (GroupTransfer, error)
	GetTransfer(ctx context.Context, transferID string) (Transfer, error)
	// ─── Activity Heatmap ─────────────────────────────
	GetTransferActivityHeatmap(ctx context.Context, senderNodeID string) ([]GetTransferActivityHeatmapRow, error)
	// ─── Speed Stats ──────────────────────────────────
	GetTransferSpeedStats(ctx context.Context, senderNodeID string) (GetTransferSpeedStatsRow, error)
	ListGroupTransfersBySession(ctx context.Context, sessionID pgtype.UUID) ([]GroupTransfer, error)
	ListTransfersByGroupID(ctx context.Context, groupTransferID pgtype.Text) ([]Transfer, error)
	ListTransfersByNode(ctx context.Context, senderNodeID string) ([]Transfer, error)
	ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error)
	SumTransferredBytes(ctx context.Context) (int64, error)
	UpdateRouteHops(ctx context.Context, arg UpdateRouteHopsParams) error
	UpdateTransferMode(ctx context.Context, arg UpdateTransferModeParams) error
	UpdateTransferProgress(ctx context.Context, arg UpdateTransferProgressParams) error
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error
}

var _ Querier = (*Queries)(nil)
