// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminListTransfers = `-- name: AdminListTransfers :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key FROM transfers ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type AdminListTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) AdminListTransfers(ctx context.Context, arg AdminListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, adminListTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
			&i.TransferMode,
			&i.GroupTransferID,
			&i.WrappedFileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeTransfer = `-- name: CompleteTransfer :exec
UPDATE transfers SET status = 3, chunks_done = total_chunks, updated_at = NOW() WHERE transfer_id = $1
`

func (q *Queries) CompleteTransfer(ctx context.Context, transferID string) error {
	_, err := q.db.Exec(ctx, completeTransfer, transferID)
	return err
}

const confirmP2PTransfer = `-- name: ConfirmP2PTransfer :exec
UPDATE transfers SET status = $2, chunks_done = $3, transfer_mode = $4, updated_at = NOW() WHERE transfer_id = $1
`

type ConfirmP2PTransferParams struct {
	TransferID   string `json:"transfer_id"`
	Status       int32  `json:"status"`
	ChunksDone   int32  `json:"chunks_done"`
	TransferMode int32  `json:"transfer_mode"`
}

func (q *Queries) ConfirmP2PTransfer(ctx context.Context, arg ConfirmP2PTransferParams) error {
	_, err := q.db.Exec(ctx, confirmP2PTransfer,
		arg.TransferID,
		arg.Status,
		arg.ChunksDone,
		arg.TransferMode,
	)
	return err
}

const countTransfers = `-- name: CountTransfers :one

SELECT COUNT(*) FROM transfers
`

// ─── Platform Stats ────────────────────────────────
func (q *Queries) CountTransfers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGroupTransfer = `-- name: CreateGroupTransfer :one

INSERT INTO group_transfers (id, session_id, sender_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, sender_ephemeral_pubkey)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, session_id, sender_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, sender_ephemeral_pubkey, created_at
`

type CreateGroupTransferParams struct {
	ID                    string      `json:"id"`
	SessionID             pgtype.UUID `json:"session_id"`
	SenderNodeID          string      `json:"sender_node_id"`
	Filename              string      `json:"filename"`
	TotalSizeBytes        int64       `json:"total_size_bytes"`
	ContentHash           string      `json:"content_hash"`
	ChunkSizeBytes        int32       `json:"chunk_size_bytes"`
	TotalChunks           int32       `json:"total_chunks"`
	SenderEphemeralPubkey []byte      `json:"sender_ephemeral_pubkey"`
}

// ─── Group Transfers ────────────────────────────────────
func (q *Queries) CreateGroupTransfer(ctx context.Context, arg CreateGroupTransferParams) (GroupTransfer, error) {
	row := q.db.QueryRow(ctx, createGroupTransfer,
		arg.ID,
		arg.SessionID,
		arg.SenderNodeID,
		arg.Filename,
		arg.TotalSizeBytes,
		arg.ContentHash,
		arg.ChunkSizeBytes,
		arg.TotalChunks,
		arg.SenderEphemeralPubkey,
	)
	var i GroupTransfer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.SenderEphemeralPubkey,
		&i.CreatedAt,
	)
	return i, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, status, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, group_transfer_id, wrapped_file_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key
`

type CreateTransferParams struct {
	TransferID            string      `json:"transfer_id"`
	SenderNodeID          string      `json:"sender_node_id"`
	ReceiverNodeID        string      `json:"receiver_node_id"`
	Filename              string      `json:"filename"`
	TotalSizeBytes        int64       `json:"total_size_bytes"`
	ContentHash           string      `json:"content_hash"`
	ChunkSizeBytes        int32       `json:"chunk_size_bytes"`
	TotalChunks           int32       `json:"total_chunks"`
	Status                int32       `json:"status"`
	EncryptionKey         string      `json:"encryption_key"`
	RouteHops             []byte      `json:"route_hops"`
	ReplicationFactor     int32       `json:"replication_factor"`
	SenderEphemeralPubkey []byte      `json:"sender_ephemeral_pubkey"`
	GroupTransferID       pgtype.Text `json:"group_transfer_id"`
	WrappedFileKey        []byte      `json:"wrapped_file_key"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.TransferID,
		arg.SenderNodeID,
		arg.ReceiverNodeID,
		arg.Filename,
		arg.TotalSizeBytes,
		arg.ContentHash,
		arg.ChunkSizeBytes,
		arg.TotalChunks,
		arg.Status,
		arg.EncryptionKey,
		arg.RouteHops,
		arg.ReplicationFactor,
		arg.SenderEphemeralPubkey,
		arg.GroupTransferID,
		arg.WrappedFileKey,
	)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.SenderNodeID,
		&i.ReceiverNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.ChunksDone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionKey,
		&i.RouteHops,
		&i.ReplicationFactor,
		&i.SenderEphemeralPubkey,
		&i.TransferMode,
		&i.GroupTransferID,
		&i.WrappedFileKey,
	)
	return i, err
}

const getGroupTransfer = `-- name: GetGroupTransfer :one
SELECT id, session_id, sender_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, sender_ephemeral_pubkey, created_at FROM group_transfers WHERE id = $1
`

func (q *Queries) GetGroupTransfer(ctx context.Context, id string) (GroupTransfer, error) {
	row := q.db.QueryRow(ctx, getGroupTransfer, id)
	var i GroupTransfer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.SenderNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.SenderEphemeralPubkey,
		&i.CreatedAt,
	)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key FROM transfers WHERE transfer_id = $1
`

func (q *Queries) GetTransfer(ctx context.Context, transferID string) (Transfer, error) {
	row := q.db.QueryRow(ctx, getTransfer, transferID)
	var i Transfer
	err := row.Scan(
		&i.TransferID,
		&i.SenderNodeID,
		&i.ReceiverNodeID,
		&i.Filename,
		&i.TotalSizeBytes,
		&i.ContentHash,
		&i.ChunkSizeBytes,
		&i.TotalChunks,
		&i.ChunksDone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EncryptionKey,
		&i.RouteHops,
		&i.ReplicationFactor,
		&i.SenderEphemeralPubkey,
		&i.TransferMode,
		&i.GroupTransferID,
		&i.WrappedFileKey,
	)
	return i, err
}

const listGroupTransfersBySession = `-- name: ListGroupTransfersBySession :many
SELECT id, session_id, sender_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, sender_ephemeral_pubkey, created_at FROM group_transfers WHERE session_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListGroupTransfersBySession(ctx context.Context, sessionID pgtype.UUID) ([]GroupTransfer, error) {
	rows, err := q.db.Query(ctx, listGroupTransfersBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupTransfer
	for rows.Next() {
		var i GroupTransfer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.SenderNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.SenderEphemeralPubkey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByGroupID = `-- name: ListTransfersByGroupID :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key FROM transfers WHERE group_transfer_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListTransfersByGroupID(ctx context.Context, groupTransferID pgtype.Text) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByGroupID, groupTransferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
			&i.TransferMode,
			&i.GroupTransferID,
			&i.WrappedFileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByNode = `-- name: ListTransfersByNode :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key FROM transfers WHERE sender_node_id = $1 OR receiver_node_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTransfersByNode(ctx context.Context, senderNodeID string) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByNode, senderNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
			&i.TransferMode,
			&i.GroupTransferID,
			&i.WrappedFileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByStatus = `-- name: ListTransfersByStatus :many
SELECT transfer_id, sender_node_id, receiver_node_id, filename, total_size_bytes, content_hash, chunk_size_bytes, total_chunks, chunks_done, status, created_at, updated_at, encryption_key, route_hops, replication_factor, sender_ephemeral_pubkey, transfer_mode, group_transfer_id, wrapped_file_key FROM transfers WHERE (sender_node_id = $1 OR receiver_node_id = $1) AND status = $2 ORDER BY created_at DESC
`

type ListTransfersByStatusParams struct {
	SenderNodeID string `json:"sender_node_id"`
	Status       int32  `json:"status"`
}

func (q *Queries) ListTransfersByStatus(ctx context.Context, arg ListTransfersByStatusParams) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByStatus, arg.SenderNodeID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.TransferID,
			&i.SenderNodeID,
			&i.ReceiverNodeID,
			&i.Filename,
			&i.TotalSizeBytes,
			&i.ContentHash,
			&i.ChunkSizeBytes,
			&i.TotalChunks,
			&i.ChunksDone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EncryptionKey,
			&i.RouteHops,
			&i.ReplicationFactor,
			&i.SenderEphemeralPubkey,
			&i.TransferMode,
			&i.GroupTransferID,
			&i.WrappedFileKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumTransferredBytes = `-- name: SumTransferredBytes :one
SELECT COALESCE(SUM(total_size_bytes), 0)::bigint FROM transfers WHERE status = 3
`

func (q *Queries) SumTransferredBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumTransferredBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRouteHops = `-- name: UpdateRouteHops :exec
UPDATE transfers SET route_hops = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateRouteHopsParams struct {
	TransferID string `json:"transfer_id"`
	RouteHops  []byte `json:"route_hops"`
}

func (q *Queries) UpdateRouteHops(ctx context.Context, arg UpdateRouteHopsParams) error {
	_, err := q.db.Exec(ctx, updateRouteHops, arg.TransferID, arg.RouteHops)
	return err
}

const updateTransferMode = `-- name: UpdateTransferMode :exec
UPDATE transfers SET transfer_mode = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateTransferModeParams struct {
	TransferID   string `json:"transfer_id"`
	TransferMode int32  `json:"transfer_mode"`
}

func (q *Queries) UpdateTransferMode(ctx context.Context, arg UpdateTransferModeParams) error {
	_, err := q.db.Exec(ctx, updateTransferMode, arg.TransferID, arg.TransferMode)
	return err
}

const updateTransferProgress = `-- name: UpdateTransferProgress :exec
UPDATE transfers SET chunks_done = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateTransferProgressParams struct {
	TransferID string `json:"transfer_id"`
	ChunksDone int32  `json:"chunks_done"`
}

func (q *Queries) UpdateTransferProgress(ctx context.Context, arg UpdateTransferProgressParams) error {
	_, err := q.db.Exec(ctx, updateTransferProgress, arg.TransferID, arg.ChunksDone)
	return err
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers SET status = $2, updated_at = NOW() WHERE transfer_id = $1
`

type UpdateTransferStatusParams struct {
	TransferID string `json:"transfer_id"`
	Status     int32  `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.TransferID, arg.Status)
	return err
}
