// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: identity/v1/identity.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_Register_FullMethodName             = "/identity.v1.IdentityService/Register"
	IdentityService_Login_FullMethodName                = "/identity.v1.IdentityService/Login"
	IdentityService_ValidateToken_FullMethodName        = "/identity.v1.IdentityService/ValidateToken"
	IdentityService_RefreshToken_FullMethodName         = "/identity.v1.IdentityService/RefreshToken"
	IdentityService_Logout_FullMethodName               = "/identity.v1.IdentityService/Logout"
	IdentityService_VerifyEmail_FullMethodName          = "/identity.v1.IdentityService/VerifyEmail"
	IdentityService_ResendVerification_FullMethodName   = "/identity.v1.IdentityService/ResendVerification"
	IdentityService_RegisterDevice_FullMethodName       = "/identity.v1.IdentityService/RegisterDevice"
	IdentityService_ListDevices_FullMethodName          = "/identity.v1.IdentityService/ListDevices"
	IdentityService_GetDevice_FullMethodName            = "/identity.v1.IdentityService/GetDevice"
	IdentityService_RevokeDevice_FullMethodName         = "/identity.v1.IdentityService/RevokeDevice"
	IdentityService_UpdateDeviceActivity_FullMethodName = "/identity.v1.IdentityService/UpdateDeviceActivity"
	IdentityService_GeneratePairingCode_FullMethodName  = "/identity.v1.IdentityService/GeneratePairingCode"
	IdentityService_RedeemPairingCode_FullMethodName    = "/identity.v1.IdentityService/RedeemPairingCode"
	IdentityService_ApprovePairing_FullMethodName       = "/identity.v1.IdentityService/ApprovePairing"
	IdentityService_CreatePeerSession_FullMethodName    = "/identity.v1.IdentityService/CreatePeerSession"
	IdentityService_ListPeerSessions_FullMethodName     = "/identity.v1.IdentityService/ListPeerSessions"
	IdentityService_ClosePeerSession_FullMethodName     = "/identity.v1.IdentityService/ClosePeerSession"
	IdentityService_JoinPeerSession_FullMethodName      = "/identity.v1.IdentityService/JoinPeerSession"
	IdentityService_LeavePeerSession_FullMethodName     = "/identity.v1.IdentityService/LeavePeerSession"
	IdentityService_ListSessionDevices_FullMethodName   = "/identity.v1.IdentityService/ListSessionDevices"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error)
	ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error)
	// Device Management
	RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
	UpdateDeviceActivity(ctx context.Context, in *UpdateDeviceActivityRequest, opts ...grpc.CallOption) (*UpdateDeviceActivityResponse, error)
	// Device Pairing
	GeneratePairingCode(ctx context.Context, in *GeneratePairingCodeRequest, opts ...grpc.CallOption) (*GeneratePairingCodeResponse, error)
	RedeemPairingCode(ctx context.Context, in *RedeemPairingCodeRequest, opts ...grpc.CallOption) (*RedeemPairingCodeResponse, error)
	ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error)
	// Peer Sessions
	CreatePeerSession(ctx context.Context, in *CreatePeerSessionRequest, opts ...grpc.CallOption) (*CreatePeerSessionResponse, error)
	ListPeerSessions(ctx context.Context, in *ListPeerSessionsRequest, opts ...grpc.CallOption) (*ListPeerSessionsResponse, error)
	ClosePeerSession(ctx context.Context, in *ClosePeerSessionRequest, opts ...grpc.CallOption) (*ClosePeerSessionResponse, error)
	JoinPeerSession(ctx context.Context, in *JoinPeerSessionRequest, opts ...grpc.CallOption) (*JoinPeerSessionResponse, error)
	LeavePeerSession(ctx context.Context, in *LeavePeerSessionRequest, opts ...grpc.CallOption) (*LeavePeerSessionResponse, error)
	ListSessionDevices(ctx context.Context, in *ListSessionDevicesRequest, opts ...grpc.CallOption) (*ListSessionDevicesResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, IdentityService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, IdentityService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ValidateToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, IdentityService_Logout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*VerifyEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyEmailResponse)
	err := c.cc.Invoke(ctx, IdentityService_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ResendVerification(ctx context.Context, in *ResendVerificationRequest, opts ...grpc.CallOption) (*ResendVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResendVerificationResponse)
	err := c.cc.Invoke(ctx, IdentityService_ResendVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceRequest, opts ...grpc.CallOption) (*RegisterDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, IdentityService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) UpdateDeviceActivity(ctx context.Context, in *UpdateDeviceActivityRequest, opts ...grpc.CallOption) (*UpdateDeviceActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeviceActivityResponse)
	err := c.cc.Invoke(ctx, IdentityService_UpdateDeviceActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GeneratePairingCode(ctx context.Context, in *GeneratePairingCodeRequest, opts ...grpc.CallOption) (*GeneratePairingCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePairingCodeResponse)
	err := c.cc.Invoke(ctx, IdentityService_GeneratePairingCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RedeemPairingCode(ctx context.Context, in *RedeemPairingCodeRequest, opts ...grpc.CallOption) (*RedeemPairingCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemPairingCodeResponse)
	err := c.cc.Invoke(ctx, IdentityService_RedeemPairingCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePairingResponse)
	err := c.cc.Invoke(ctx, IdentityService_ApprovePairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) CreatePeerSession(ctx context.Context, in *CreatePeerSessionRequest, opts ...grpc.CallOption) (*CreatePeerSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePeerSessionResponse)
	err := c.cc.Invoke(ctx, IdentityService_CreatePeerSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ListPeerSessions(ctx context.Context, in *ListPeerSessionsRequest, opts ...grpc.CallOption) (*ListPeerSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeerSessionsResponse)
	err := c.cc.Invoke(ctx, IdentityService_ListPeerSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ClosePeerSession(ctx context.Context, in *ClosePeerSessionRequest, opts ...grpc.CallOption) (*ClosePeerSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClosePeerSessionResponse)
	err := c.cc.Invoke(ctx, IdentityService_ClosePeerSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) JoinPeerSession(ctx context.Context, in *JoinPeerSessionRequest, opts ...grpc.CallOption) (*JoinPeerSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinPeerSessionResponse)
	err := c.cc.Invoke(ctx, IdentityService_JoinPeerSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) LeavePeerSession(ctx context.Context, in *LeavePeerSessionRequest, opts ...grpc.CallOption) (*LeavePeerSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeavePeerSessionResponse)
	err := c.cc.Invoke(ctx, IdentityService_LeavePeerSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ListSessionDevices(ctx context.Context, in *ListSessionDevicesRequest, opts ...grpc.CallOption) (*ListSessionDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionDevicesResponse)
	err := c.cc.Invoke(ctx, IdentityService_ListSessionDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations should embed UnimplementedIdentityServiceServer
// for forward compatibility.
type IdentityServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error)
	ResendVerification(context.Context, *ResendVerificationRequest) (*ResendVerificationResponse, error)
	// Device Management
	RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	UpdateDeviceActivity(context.Context, *UpdateDeviceActivityRequest) (*UpdateDeviceActivityResponse, error)
	// Device Pairing
	GeneratePairingCode(context.Context, *GeneratePairingCodeRequest) (*GeneratePairingCodeResponse, error)
	RedeemPairingCode(context.Context, *RedeemPairingCodeRequest) (*RedeemPairingCodeResponse, error)
	ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error)
	// Peer Sessions
	CreatePeerSession(context.Context, *CreatePeerSessionRequest) (*CreatePeerSessionResponse, error)
	ListPeerSessions(context.Context, *ListPeerSessionsRequest) (*ListPeerSessionsResponse, error)
	ClosePeerSession(context.Context, *ClosePeerSessionRequest) (*ClosePeerSessionResponse, error)
	JoinPeerSession(context.Context, *JoinPeerSessionRequest) (*JoinPeerSessionResponse, error)
	LeavePeerSession(context.Context, *LeavePeerSessionRequest) (*LeavePeerSessionResponse, error)
	ListSessionDevices(context.Context, *ListSessionDevicesRequest) (*ListSessionDevicesResponse, error)
}

// UnimplementedIdentityServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedIdentityServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityServiceServer) ValidateToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedIdentityServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedIdentityServiceServer) Logout(context.Context, *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedIdentityServiceServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*VerifyEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedIdentityServiceServer) ResendVerification(context.Context, *ResendVerificationRequest) (*ResendVerificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResendVerification not implemented")
}
func (UnimplementedIdentityServiceServer) RegisterDevice(context.Context, *RegisterDeviceRequest) (*RegisterDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedIdentityServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedIdentityServiceServer) GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDevice not implemented")
}
func (UnimplementedIdentityServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedIdentityServiceServer) UpdateDeviceActivity(context.Context, *UpdateDeviceActivityRequest) (*UpdateDeviceActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeviceActivity not implemented")
}
func (UnimplementedIdentityServiceServer) GeneratePairingCode(context.Context, *GeneratePairingCodeRequest) (*GeneratePairingCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePairingCode not implemented")
}
func (UnimplementedIdentityServiceServer) RedeemPairingCode(context.Context, *RedeemPairingCodeRequest) (*RedeemPairingCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemPairingCode not implemented")
}
func (UnimplementedIdentityServiceServer) ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApprovePairing not implemented")
}
func (UnimplementedIdentityServiceServer) CreatePeerSession(context.Context, *CreatePeerSessionRequest) (*CreatePeerSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePeerSession not implemented")
}
func (UnimplementedIdentityServiceServer) ListPeerSessions(context.Context, *ListPeerSessionsRequest) (*ListPeerSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPeerSessions not implemented")
}
func (UnimplementedIdentityServiceServer) ClosePeerSession(context.Context, *ClosePeerSessionRequest) (*ClosePeerSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClosePeerSession not implemented")
}
func (UnimplementedIdentityServiceServer) JoinPeerSession(context.Context, *JoinPeerSessionRequest) (*JoinPeerSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinPeerSession not implemented")
}
func (UnimplementedIdentityServiceServer) LeavePeerSession(context.Context, *LeavePeerSessionRequest) (*LeavePeerSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeavePeerSession not implemented")
}
func (UnimplementedIdentityServiceServer) ListSessionDevices(context.Context, *ListSessionDevicesRequest) (*ListSessionDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessionDevices not implemented")
}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ValidateToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Logout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ResendVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ResendVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ResendVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ResendVerification(ctx, req.(*ResendVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterDevice(ctx, req.(*RegisterDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_UpdateDeviceActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).UpdateDeviceActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_UpdateDeviceActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).UpdateDeviceActivity(ctx, req.(*UpdateDeviceActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GeneratePairingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePairingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GeneratePairingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GeneratePairingCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GeneratePairingCode(ctx, req.(*GeneratePairingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RedeemPairingCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemPairingCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RedeemPairingCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RedeemPairingCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RedeemPairingCode(ctx, req.(*RedeemPairingCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ApprovePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ApprovePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ApprovePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ApprovePairing(ctx, req.(*ApprovePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_CreatePeerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePeerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CreatePeerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CreatePeerSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CreatePeerSession(ctx, req.(*CreatePeerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ListPeerSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeerSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ListPeerSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ListPeerSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ListPeerSessions(ctx, req.(*ListPeerSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ClosePeerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePeerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ClosePeerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ClosePeerSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ClosePeerSession(ctx, req.(*ClosePeerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_JoinPeerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPeerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).JoinPeerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_JoinPeerSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).JoinPeerSession(ctx, req.(*JoinPeerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_LeavePeerSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeavePeerSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).LeavePeerSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_LeavePeerSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).LeavePeerSession(ctx, req.(*LeavePeerSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ListSessionDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ListSessionDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ListSessionDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ListSessionDevices(ctx, req.(*ListSessionDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _IdentityService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _IdentityService_Login_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _IdentityService_ValidateToken_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _IdentityService_RefreshToken_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _IdentityService_Logout_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _IdentityService_VerifyEmail_Handler,
		},
		{
			MethodName: "ResendVerification",
			Handler:    _IdentityService_ResendVerification_Handler,
		},
		{
			MethodName: "RegisterDevice",
			Handler:    _IdentityService_RegisterDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _IdentityService_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _IdentityService_GetDevice_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _IdentityService_RevokeDevice_Handler,
		},
		{
			MethodName: "UpdateDeviceActivity",
			Handler:    _IdentityService_UpdateDeviceActivity_Handler,
		},
		{
			MethodName: "GeneratePairingCode",
			Handler:    _IdentityService_GeneratePairingCode_Handler,
		},
		{
			MethodName: "RedeemPairingCode",
			Handler:    _IdentityService_RedeemPairingCode_Handler,
		},
		{
			MethodName: "ApprovePairing",
			Handler:    _IdentityService_ApprovePairing_Handler,
		},
		{
			MethodName: "CreatePeerSession",
			Handler:    _IdentityService_CreatePeerSession_Handler,
		},
		{
			MethodName: "ListPeerSessions",
			Handler:    _IdentityService_ListPeerSessions_Handler,
		},
		{
			MethodName: "ClosePeerSession",
			Handler:    _IdentityService_ClosePeerSession_Handler,
		},
		{
			MethodName: "JoinPeerSession",
			Handler:    _IdentityService_JoinPeerSession_Handler,
		},
		{
			MethodName: "LeavePeerSession",
			Handler:    _IdentityService_LeavePeerSession_Handler,
		},
		{
			MethodName: "ListSessionDevices",
			Handler:    _IdentityService_ListSessionDevices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "identity/v1/identity.proto",
}
