// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: relay/v1/relay.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayService_RelayChunk_FullMethodName = "/relay.v1.RelayService/RelayChunk"
	RelayService_FetchChunk_FullMethodName = "/relay.v1.RelayService/FetchChunk"
	RelayService_Ping_FullMethodName       = "/relay.v1.RelayService/Ping"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayServiceClient interface {
	// Forwards an encrypted chunk to the next hop in the route.
	// If this node is the final destination, the chunk is stored locally.
	RelayChunk(ctx context.Context, in *RelayChunkRequest, opts ...grpc.CallOption) (*RelayChunkResponse, error)
	// Pulls a specific chunk from a peer (used for replication recovery).
	FetchChunk(ctx context.Context, in *FetchChunkRequest, opts ...grpc.CallOption) (*FetchChunkResponse, error)
	// Health probe used by circuit breaker before forwarding.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) RelayChunk(ctx context.Context, in *RelayChunkRequest, opts ...grpc.CallOption) (*RelayChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayChunkResponse)
	err := c.cc.Invoke(ctx, RelayService_RelayChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) FetchChunk(ctx context.Context, in *FetchChunkRequest, opts ...grpc.CallOption) (*FetchChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchChunkResponse)
	err := c.cc.Invoke(ctx, RelayService_FetchChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, RelayService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServiceServer is the server API for RelayService service.
// All implementations should embed UnimplementedRelayServiceServer
// for forward compatibility.
type RelayServiceServer interface {
	// Forwards an encrypted chunk to the next hop in the route.
	// If this node is the final destination, the chunk is stored locally.
	RelayChunk(context.Context, *RelayChunkRequest) (*RelayChunkResponse, error)
	// Pulls a specific chunk from a peer (used for replication recovery).
	FetchChunk(context.Context, *FetchChunkRequest) (*FetchChunkResponse, error)
	// Health probe used by circuit breaker before forwarding.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedRelayServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) RelayChunk(context.Context, *RelayChunkRequest) (*RelayChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelayChunk not implemented")
}
func (UnimplementedRelayServiceServer) FetchChunk(context.Context, *FetchChunkRequest) (*FetchChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchChunk not implemented")
}
func (UnimplementedRelayServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRelayServiceServer) testEmbeddedByValue() {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_RelayChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).RelayChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_RelayChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).RelayChunk(ctx, req.(*RelayChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_FetchChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).FetchChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_FetchChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).FetchChunk(ctx, req.(*FetchChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayChunk",
			Handler:    _RelayService_RelayChunk_Handler,
		},
		{
			MethodName: "FetchChunk",
			Handler:    _RelayService_FetchChunk_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _RelayService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay/v1/relay.proto",
}
