// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relay/v1/relay.proto

package relayv1

import (
	v1 "github.com/saitddundar/vinctum-core/proto/routing/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelayChunkRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TransferId        string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkIndex        int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data              []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                     // Encrypted chunk data
	ChunkHash         string                 `protobuf:"bytes,4,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`                          // SHA-256 of encrypted data
	RemainingHops     []*v1.RouteHop         `protobuf:"bytes,5,rep,name=remaining_hops,json=remainingHops,proto3" json:"remaining_hops,omitempty"`              // Hops still to traverse
	ReplicationFactor int32                  `protobuf:"varint,6,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"` // Number of copies to store (default: 1)
	Ttl               int32                  `protobuf:"varint,7,opt,name=ttl,proto3" json:"ttl,omitempty"`                                                      // Decremented each hop, drop if 0
	EncryptionKey     string                 `protobuf:"bytes,8,opt,name=encryption_key,json=encryptionKey,proto3" json:"encryption_key,omitempty"`              // E2E key for final-destination verification
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelayChunkRequest) Reset() {
	*x = RelayChunkRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChunkRequest) ProtoMessage() {}

func (x *RelayChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChunkRequest.ProtoReflect.Descriptor instead.
func (*RelayChunkRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *RelayChunkRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *RelayChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *RelayChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RelayChunkRequest) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *RelayChunkRequest) GetRemainingHops() []*v1.RouteHop {
	if x != nil {
		return x.RemainingHops
	}
	return nil
}

func (x *RelayChunkRequest) GetReplicationFactor() int32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *RelayChunkRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *RelayChunkRequest) GetEncryptionKey() string {
	if x != nil {
		return x.EncryptionKey
	}
	return ""
}

type RelayChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Node that confirmed storage/relay
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayChunkResponse) Reset() {
	*x = RelayChunkResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayChunkResponse) ProtoMessage() {}

func (x *RelayChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayChunkResponse.ProtoReflect.Descriptor instead.
func (*RelayChunkResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *RelayChunkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RelayChunkResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RelayChunkResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FetchChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChunkRequest) Reset() {
	*x = FetchChunkRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChunkRequest) ProtoMessage() {}

func (x *FetchChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChunkRequest.ProtoReflect.Descriptor instead.
func (*FetchChunkRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *FetchChunkRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FetchChunkRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type FetchChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkHash     string                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchChunkResponse) Reset() {
	*x = FetchChunkResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchChunkResponse) ProtoMessage() {}

func (x *FetchChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchChunkResponse.ProtoReflect.Descriptor instead.
func (*FetchChunkResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *FetchChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FetchChunkResponse) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix millis
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_relay_v1_relay_proto protoreflect.FileDescriptor

const file_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x14relay/v1/relay.proto\x12\brelay.v1\x1a\x18routing/v1/routing.proto\"\xad\x02\n" +
	"\x11RelayChunkRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x04 \x01(\tR\tchunkHash\x12;\n" +
	"\x0eremaining_hops\x18\x05 \x03(\v2\x14.routing.v1.RouteHopR\rremainingHops\x12-\n" +
	"\x12replication_factor\x18\x06 \x01(\x05R\x11replicationFactor\x12\x10\n" +
	"\x03ttl\x18\a \x01(\x05R\x03ttl\x12%\n" +
	"\x0eencryption_key\x18\b \x01(\tR\rencryptionKey\"l\n" +
	"\x12RelayChunkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"U\n" +
	"\x11FetchChunkRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\"G\n" +
	"\x12FetchChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tR\tchunkHash\"&\n" +
	"\vPingRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"E\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xd7\x01\n" +
	"\fRelayService\x12G\n" +
	"\n" +
	"RelayChunk\x12\x1b.relay.v1.RelayChunkRequest\x1a\x1c.relay.v1.RelayChunkResponse\x12G\n" +
	"\n" +
	"FetchChunk\x12\x1b.relay.v1.FetchChunkRequest\x1a\x1c.relay.v1.FetchChunkResponse\x125\n" +
	"\x04Ping\x12\x15.relay.v1.PingRequest\x1a\x16.relay.v1.PingResponseB<Z:github.com/saitddundar/vinctum-core/proto/relay/v1;relayv1b\x06proto3"

var (
	file_relay_v1_relay_proto_rawDescOnce sync.Once
	file_relay_v1_relay_proto_rawDescData []byte
)

func file_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)))
	})
	return file_relay_v1_relay_proto_rawDescData
}

var file_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_relay_v1_relay_proto_goTypes = []any{
	(*RelayChunkRequest)(nil),  // 0: relay.v1.RelayChunkRequest
	(*RelayChunkResponse)(nil), // 1: relay.v1.RelayChunkResponse
	(*FetchChunkRequest)(nil),  // 2: relay.v1.FetchChunkRequest
	(*FetchChunkResponse)(nil), // 3: relay.v1.FetchChunkResponse
	(*PingRequest)(nil),        // 4: relay.v1.PingRequest
	(*PingResponse)(nil),       // 5: relay.v1.PingResponse
	(*v1.RouteHop)(nil),        // 6: routing.v1.RouteHop
}
var file_relay_v1_relay_proto_depIdxs = []int32{
	6, // 0: relay.v1.RelayChunkRequest.remaining_hops:type_name -> routing.v1.RouteHop
	0, // 1: relay.v1.RelayService.RelayChunk:input_type -> relay.v1.RelayChunkRequest
	2, // 2: relay.v1.RelayService.FetchChunk:input_type -> relay.v1.FetchChunkRequest
	4, // 3: relay.v1.RelayService.Ping:input_type -> relay.v1.PingRequest
	1, // 4: relay.v1.RelayService.RelayChunk:output_type -> relay.v1.RelayChunkResponse
	3, // 5: relay.v1.RelayService.FetchChunk:output_type -> relay.v1.FetchChunkResponse
	5, // 6: relay.v1.RelayService.Ping:output_type -> relay.v1.PingResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relay_v1_relay_proto_init() }
func file_relay_v1_relay_proto_init() {
	if File_relay_v1_relay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_relay_v1_relay_proto_depIdxs,
		MessageInfos:      file_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_relay_v1_relay_proto = out.File
	file_relay_v1_relay_proto_goTypes = nil
	file_relay_v1_relay_proto_depIdxs = nil
}
