// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :exec
UPDATE friends SET status = 'accepted', updated_at = NOW()
WHERE id = $1::uuid AND addressee_id = $2::uuid AND status = 'pending'
`

type AcceptFriendRequestParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) error {
	_, err := q.db.Exec(ctx, acceptFriendRequest, arg.Column1, arg.Column2)
	return err
}

const addDeviceToSession = `-- name: AddDeviceToSession :exec
INSERT INTO peer_session_devices (session_id, device_id) VALUES ($1, $2)
ON CONFLICT (session_id, device_id) DO UPDATE SET left_at = NULL
`

type AddDeviceToSessionParams struct {
	SessionID string `json:"session_id"`
	DeviceID  string `json:"device_id"`
}

func (q *Queries) AddDeviceToSession(ctx context.Context, arg AddDeviceToSessionParams) error {
	_, err := q.db.Exec(ctx, addDeviceToSession, arg.SessionID, arg.DeviceID)
	return err
}

const approveDevice = `-- name: ApproveDevice :exec
UPDATE devices SET is_approved = TRUE, approved_at = NOW(), approved_by = $2::uuid
WHERE id = $1::uuid
`

type ApproveDeviceParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) ApproveDevice(ctx context.Context, arg ApproveDeviceParams) error {
	_, err := q.db.Exec(ctx, approveDevice, arg.Column1, arg.Column2)
	return err
}

const closePeerSession = `-- name: ClosePeerSession :exec
UPDATE peer_sessions SET is_active = FALSE, closed_at = NOW() WHERE id = $1::uuid AND user_id = $2::uuid
`

type ClosePeerSessionParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) ClosePeerSession(ctx context.Context, arg ClosePeerSessionParams) error {
	_, err := q.db.Exec(ctx, closePeerSession, arg.Column1, arg.Column2)
	return err
}

const countPendingFriendRequests = `-- name: CountPendingFriendRequests :one
SELECT COUNT(*) FROM friends WHERE addressee_id = $1::uuid AND status = 'pending'
`

func (q *Queries) CountPendingFriendRequests(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingFriendRequests, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one

INSERT INTO devices (user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, is_public)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, last_active, created_at, revoked_at, is_public
`

type CreateDeviceParams struct {
	UserID      string             `json:"user_id"`
	Name        string             `json:"name"`
	DeviceType  string             `json:"device_type"`
	NodeID      pgtype.Text        `json:"node_id"`
	Fingerprint string             `json:"fingerprint"`
	IsApproved  bool               `json:"is_approved"`
	ApprovedAt  pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy  pgtype.UUID        `json:"approved_by"`
	IsPublic    bool               `json:"is_public"`
}

// ─── Devices ────────────────────────────────────────
func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Name,
		arg.DeviceType,
		arg.NodeID,
		arg.Fingerprint,
		arg.IsApproved,
		arg.ApprovedAt,
		arg.ApprovedBy,
		arg.IsPublic,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.NodeID,
		&i.Fingerprint,
		&i.IsApproved,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.LastActive,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsPublic,
	)
	return i, err
}

const createFriendRequest = `-- name: CreateFriendRequest :one

INSERT INTO friends (requester_id, addressee_id, status)
VALUES ($1::uuid, $2::uuid, 'pending')
RETURNING id, requester_id, addressee_id, status, created_at, updated_at
`

type CreateFriendRequestParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

// ─── Friends ────────────────────────────────────────
func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friend, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.Column1, arg.Column2)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPeerSession = `-- name: CreatePeerSession :one

INSERT INTO peer_sessions (user_id, name) VALUES ($1, $2) RETURNING id, user_id, name, is_active, created_at, closed_at
`

type CreatePeerSessionParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

// ─── Peer Sessions ──────────────────────────────────
func (q *Queries) CreatePeerSession(ctx context.Context, arg CreatePeerSessionParams) (PeerSession, error) {
	row := q.db.QueryRow(ctx, createPeerSession, arg.UserID, arg.Name)
	var i PeerSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, created_at, email_verified, verification_token, verification_expires_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getDeviceByFingerprint = `-- name: GetDeviceByFingerprint :one
SELECT id, user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, last_active, created_at, revoked_at, is_public FROM devices WHERE user_id = $1::uuid AND fingerprint = $2 AND revoked_at IS NULL
`

type GetDeviceByFingerprintParams struct {
	Column1     string `json:"column_1"`
	Fingerprint string `json:"fingerprint"`
}

func (q *Queries) GetDeviceByFingerprint(ctx context.Context, arg GetDeviceByFingerprintParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByFingerprint, arg.Column1, arg.Fingerprint)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.NodeID,
		&i.Fingerprint,
		&i.IsApproved,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.LastActive,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsPublic,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, last_active, created_at, revoked_at, is_public FROM devices WHERE id = $1::uuid AND revoked_at IS NULL
`

func (q *Queries) GetDeviceByID(ctx context.Context, dollar_1 string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, dollar_1)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.DeviceType,
		&i.NodeID,
		&i.Fingerprint,
		&i.IsApproved,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.LastActive,
		&i.CreatedAt,
		&i.RevokedAt,
		&i.IsPublic,
	)
	return i, err
}

const getDeviceKey = `-- name: GetDeviceKey :one
SELECT device_id, kex_algo, kex_public_key, created_at, rotated_at FROM device_keys WHERE device_id = $1::uuid
`

func (q *Queries) GetDeviceKey(ctx context.Context, dollar_1 string) (DeviceKey, error) {
	row := q.db.QueryRow(ctx, getDeviceKey, dollar_1)
	var i DeviceKey
	err := row.Scan(
		&i.DeviceID,
		&i.KexAlgo,
		&i.KexPublicKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getDeviceKeyByNodeID = `-- name: GetDeviceKeyByNodeID :one
SELECT dk.device_id, dk.kex_algo, dk.kex_public_key, dk.created_at, dk.rotated_at FROM device_keys dk
JOIN devices d ON d.id = dk.device_id
WHERE d.node_id = $1 AND d.revoked_at IS NULL AND d.is_approved = TRUE
`

func (q *Queries) GetDeviceKeyByNodeID(ctx context.Context, nodeID pgtype.Text) (DeviceKey, error) {
	row := q.db.QueryRow(ctx, getDeviceKeyByNodeID, nodeID)
	var i DeviceKey
	err := row.Scan(
		&i.DeviceID,
		&i.KexAlgo,
		&i.KexPublicKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getFriendship = `-- name: GetFriendship :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at FROM friends WHERE id = $1::uuid
`

func (q *Queries) GetFriendship(ctx context.Context, dollar_1 string) (Friend, error) {
	row := q.db.QueryRow(ctx, getFriendship, dollar_1)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipBetween = `-- name: GetFriendshipBetween :one
SELECT id, requester_id, addressee_id, status, created_at, updated_at FROM friends
WHERE (requester_id = $1::uuid AND addressee_id = $2::uuid)
   OR (requester_id = $2::uuid AND addressee_id = $1::uuid)
LIMIT 1
`

type GetFriendshipBetweenParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) GetFriendshipBetween(ctx context.Context, arg GetFriendshipBetweenParams) (Friend, error) {
	row := q.db.QueryRow(ctx, getFriendshipBetween, arg.Column1, arg.Column2)
	var i Friend
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeerSession = `-- name: GetPeerSession :one
SELECT id, user_id, name, is_active, created_at, closed_at FROM peer_sessions WHERE id = $1::uuid
`

func (q *Queries) GetPeerSession(ctx context.Context, dollar_1 string) (PeerSession, error) {
	row := q.db.QueryRow(ctx, getPeerSession, dollar_1)
	var i PeerSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, email_verified, verification_token, verification_expires_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, email_verified, verification_token, verification_expires_at FROM users WHERE id = $1::uuid
`

func (q *Queries) GetUserByID(ctx context.Context, dollar_1 string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, dollar_1)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, username, email, password_hash, created_at, email_verified, verification_token, verification_expires_at FROM users
WHERE verification_token = $1
  AND verification_expires_at > NOW()
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, verificationToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, verificationToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationExpiresAt,
	)
	return i, err
}

const listAcceptedFriends = `-- name: ListAcceptedFriends :many
SELECT f.id, f.requester_id, f.addressee_id, f.status, f.created_at, f.updated_at, u.id AS friend_user_id, u.username AS friend_username, u.email AS friend_email
FROM friends f
JOIN users u ON u.id = CASE WHEN f.requester_id = $1::uuid THEN f.addressee_id ELSE f.requester_id END
WHERE (f.requester_id = $1::uuid OR f.addressee_id = $1::uuid) AND f.status = 'accepted'
ORDER BY f.updated_at DESC
`

type ListAcceptedFriendsRow struct {
	ID             string    `json:"id"`
	RequesterID    string    `json:"requester_id"`
	AddresseeID    string    `json:"addressee_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	FriendUserID   string    `json:"friend_user_id"`
	FriendUsername string    `json:"friend_username"`
	FriendEmail    string    `json:"friend_email"`
}

func (q *Queries) ListAcceptedFriends(ctx context.Context, dollar_1 string) ([]ListAcceptedFriendsRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriends, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcceptedFriendsRow
	for rows.Next() {
		var i ListAcceptedFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FriendUserID,
			&i.FriendUsername,
			&i.FriendEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePeerSessions = `-- name: ListActivePeerSessions :many
SELECT id, user_id, name, is_active, created_at, closed_at FROM peer_sessions WHERE user_id = $1::uuid AND is_active = TRUE ORDER BY created_at DESC
`

func (q *Queries) ListActivePeerSessions(ctx context.Context, dollar_1 string) ([]PeerSession, error) {
	rows, err := q.db.Query(ctx, listActivePeerSessions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerSession
	for rows.Next() {
		var i PeerSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUser = `-- name: ListDevicesByUser :many
SELECT id, user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, last_active, created_at, revoked_at, is_public FROM devices WHERE user_id = $1::uuid AND revoked_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListDevicesByUser(ctx context.Context, dollar_1 string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUser, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceType,
			&i.NodeID,
			&i.Fingerprint,
			&i.IsApproved,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.LastActive,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevicesByUserPublic = `-- name: ListDevicesByUserPublic :many
SELECT id, user_id, name, device_type, node_id, fingerprint, is_approved, approved_at, approved_by, last_active, created_at, revoked_at, is_public FROM devices WHERE user_id = $1::uuid AND revoked_at IS NULL AND is_approved = TRUE AND is_public = TRUE
ORDER BY last_active DESC
`

func (q *Queries) ListDevicesByUserPublic(ctx context.Context, dollar_1 string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserPublic, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceType,
			&i.NodeID,
			&i.Fingerprint,
			&i.IsApproved,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.LastActive,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingFriendRequests = `-- name: ListPendingFriendRequests :many
SELECT f.id, f.requester_id, f.addressee_id, f.status, f.created_at, f.updated_at, u.id AS friend_user_id, u.username AS friend_username, u.email AS friend_email
FROM friends f
JOIN users u ON u.id = f.requester_id
WHERE f.addressee_id = $1::uuid AND f.status = 'pending'
ORDER BY f.created_at DESC
`

type ListPendingFriendRequestsRow struct {
	ID             string    `json:"id"`
	RequesterID    string    `json:"requester_id"`
	AddresseeID    string    `json:"addressee_id"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	FriendUserID   string    `json:"friend_user_id"`
	FriendUsername string    `json:"friend_username"`
	FriendEmail    string    `json:"friend_email"`
}

func (q *Queries) ListPendingFriendRequests(ctx context.Context, dollar_1 string) ([]ListPendingFriendRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingFriendRequests, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingFriendRequestsRow
	for rows.Next() {
		var i ListPendingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AddresseeID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FriendUserID,
			&i.FriendUsername,
			&i.FriendEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDeviceKeys = `-- name: ListSessionDeviceKeys :many
SELECT dk.device_id, dk.kex_algo, dk.kex_public_key, dk.created_at, dk.rotated_at FROM device_keys dk
JOIN peer_session_devices psd ON dk.device_id = psd.device_id
JOIN devices d ON d.id = dk.device_id
WHERE psd.session_id = $1::uuid AND psd.left_at IS NULL AND d.revoked_at IS NULL
`

func (q *Queries) ListSessionDeviceKeys(ctx context.Context, dollar_1 string) ([]DeviceKey, error) {
	rows, err := q.db.Query(ctx, listSessionDeviceKeys, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceKey
	for rows.Next() {
		var i DeviceKey
		if err := rows.Scan(
			&i.DeviceID,
			&i.KexAlgo,
			&i.KexPublicKey,
			&i.CreatedAt,
			&i.RotatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionDevices = `-- name: ListSessionDevices :many
SELECT d.id, d.user_id, d.name, d.device_type, d.node_id, d.fingerprint, d.is_approved, d.approved_at, d.approved_by, d.last_active, d.created_at, d.revoked_at, d.is_public FROM devices d
JOIN peer_session_devices psd ON d.id = psd.device_id
WHERE psd.session_id = $1::uuid AND psd.left_at IS NULL AND d.revoked_at IS NULL
`

func (q *Queries) ListSessionDevices(ctx context.Context, dollar_1 string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listSessionDevices, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.DeviceType,
			&i.NodeID,
			&i.Fingerprint,
			&i.IsApproved,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.LastActive,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.IsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectDevice = `-- name: RejectDevice :exec
UPDATE devices SET revoked_at = NOW() WHERE id = $1::uuid AND is_approved = FALSE
`

func (q *Queries) RejectDevice(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, rejectDevice, dollar_1)
	return err
}

const rejectFriendRequest = `-- name: RejectFriendRequest :exec
UPDATE friends SET status = 'rejected', updated_at = NOW()
WHERE id = $1::uuid AND addressee_id = $2::uuid AND status = 'pending'
`

type RejectFriendRequestParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) RejectFriendRequest(ctx context.Context, arg RejectFriendRequestParams) error {
	_, err := q.db.Exec(ctx, rejectFriendRequest, arg.Column1, arg.Column2)
	return err
}

const removeDeviceFromSession = `-- name: RemoveDeviceFromSession :exec
UPDATE peer_session_devices SET left_at = NOW() WHERE session_id = $1::uuid AND device_id = $2::uuid
`

type RemoveDeviceFromSessionParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) RemoveDeviceFromSession(ctx context.Context, arg RemoveDeviceFromSessionParams) error {
	_, err := q.db.Exec(ctx, removeDeviceFromSession, arg.Column1, arg.Column2)
	return err
}

const removeFriend = `-- name: RemoveFriend :exec
DELETE FROM friends WHERE id = $1::uuid
AND (requester_id = $2::uuid OR addressee_id = $2::uuid)
`

type RemoveFriendParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) RemoveFriend(ctx context.Context, arg RemoveFriendParams) error {
	_, err := q.db.Exec(ctx, removeFriend, arg.Column1, arg.Column2)
	return err
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE devices SET revoked_at = NOW() WHERE id = $1::uuid AND user_id = $2::uuid
`

type RevokeDeviceParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.Column1, arg.Column2)
	return err
}

const searchUsersByUsername = `-- name: SearchUsersByUsername :many
SELECT id, username, email FROM users
WHERE username ILIKE '%' || $1 || '%' AND id != $2::uuid
LIMIT 20
`

type SearchUsersByUsernameParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Column2 string      `json:"column_2"`
}

type SearchUsersByUsernameRow struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) SearchUsersByUsername(ctx context.Context, arg SearchUsersByUsernameParams) ([]SearchUsersByUsernameRow, error) {
	rows, err := q.db.Query(ctx, searchUsersByUsername, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersByUsernameRow
	for rows.Next() {
		var i SearchUsersByUsernameRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVerificationToken = `-- name: SetVerificationToken :exec
UPDATE users
SET verification_token = $2, verification_expires_at = $3
WHERE id = $1::uuid
`

type SetVerificationTokenParams struct {
	Column1               string             `json:"column_1"`
	VerificationToken     pgtype.Text        `json:"verification_token"`
	VerificationExpiresAt pgtype.Timestamptz `json:"verification_expires_at"`
}

func (q *Queries) SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, setVerificationToken, arg.Column1, arg.VerificationToken, arg.VerificationExpiresAt)
	return err
}

const updateDeviceActivity = `-- name: UpdateDeviceActivity :exec
UPDATE devices SET last_active = NOW(), node_id = COALESCE($2, node_id)
WHERE id = $1::uuid AND revoked_at IS NULL
`

type UpdateDeviceActivityParams struct {
	Column1 string      `json:"column_1"`
	NodeID  pgtype.Text `json:"node_id"`
}

func (q *Queries) UpdateDeviceActivity(ctx context.Context, arg UpdateDeviceActivityParams) error {
	_, err := q.db.Exec(ctx, updateDeviceActivity, arg.Column1, arg.NodeID)
	return err
}

const updateDeviceVisibility = `-- name: UpdateDeviceVisibility :exec
UPDATE devices SET is_public = $2 WHERE id = $1::uuid AND revoked_at IS NULL
`

type UpdateDeviceVisibilityParams struct {
	Column1  string `json:"column_1"`
	IsPublic bool   `json:"is_public"`
}

func (q *Queries) UpdateDeviceVisibility(ctx context.Context, arg UpdateDeviceVisibilityParams) error {
	_, err := q.db.Exec(ctx, updateDeviceVisibility, arg.Column1, arg.IsPublic)
	return err
}

const upsertDeviceKey = `-- name: UpsertDeviceKey :one

INSERT INTO device_keys (device_id, kex_algo, kex_public_key)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (device_id) DO UPDATE
    SET kex_algo       = EXCLUDED.kex_algo,
        kex_public_key = EXCLUDED.kex_public_key,
        rotated_at     = NOW()
RETURNING device_id, kex_algo, kex_public_key, created_at, rotated_at
`

type UpsertDeviceKeyParams struct {
	Column1      string `json:"column_1"`
	KexAlgo      string `json:"kex_algo"`
	KexPublicKey []byte `json:"kex_public_key"`
}

// ─── Device Keys ────────────────────────────────────
func (q *Queries) UpsertDeviceKey(ctx context.Context, arg UpsertDeviceKeyParams) (DeviceKey, error) {
	row := q.db.QueryRow(ctx, upsertDeviceKey, arg.Column1, arg.KexAlgo, arg.KexPublicKey)
	var i DeviceKey
	err := row.Scan(
		&i.DeviceID,
		&i.KexAlgo,
		&i.KexPublicKey,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET email_verified = TRUE, verification_token = NULL, verification_expires_at = NULL
WHERE id = $1::uuid
`

func (q *Queries) VerifyUserEmail(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, dollar_1)
	return err
}
