// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: p2p/v1/p2p.proto

package p2pv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent at the start of a P2P transfer stream to identify the session.
type P2PTransferHeader struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	TotalChunks    int32                  `protobuf:"varint,2,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,3,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	ContentHash    string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *P2PTransferHeader) Reset() {
	*x = P2PTransferHeader{}
	mi := &file_p2p_v1_p2p_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PTransferHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PTransferHeader) ProtoMessage() {}

func (x *P2PTransferHeader) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_v1_p2p_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PTransferHeader.ProtoReflect.Descriptor instead.
func (*P2PTransferHeader) Descriptor() ([]byte, []int) {
	return file_p2p_v1_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *P2PTransferHeader) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *P2PTransferHeader) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *P2PTransferHeader) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *P2PTransferHeader) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// Each chunk sent over the stream.
type P2PChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // E2E encrypted ciphertext
	ChunkHash     string                 `protobuf:"bytes,3,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"` // SHA-256 of ciphertext
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PChunk) Reset() {
	*x = P2PChunk{}
	mi := &file_p2p_v1_p2p_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PChunk) ProtoMessage() {}

func (x *P2PChunk) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_v1_p2p_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PChunk.ProtoReflect.Descriptor instead.
func (*P2PChunk) Descriptor() ([]byte, []int) {
	return file_p2p_v1_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *P2PChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *P2PChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *P2PChunk) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *P2PChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Sent by receiver after processing each chunk for flow control.
type P2PChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex    int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *P2PChunkAck) Reset() {
	*x = P2PChunkAck{}
	mi := &file_p2p_v1_p2p_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *P2PChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2PChunkAck) ProtoMessage() {}

func (x *P2PChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_p2p_v1_p2p_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2PChunkAck.ProtoReflect.Descriptor instead.
func (*P2PChunkAck) Descriptor() ([]byte, []int) {
	return file_p2p_v1_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *P2PChunkAck) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *P2PChunkAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *P2PChunkAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_p2p_v1_p2p_proto protoreflect.FileDescriptor

const file_p2p_v1_p2p_proto_rawDesc = "" +
	"\n" +
	"\x10p2p/v1/p2p.proto\x12\x06p2p.v1\"\xa4\x01\n" +
	"\x11P2PTransferHeader\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12!\n" +
	"\ftotal_chunks\x18\x02 \x01(\x05R\vtotalChunks\x12(\n" +
	"\x10total_size_bytes\x18\x03 \x01(\x03R\x0etotalSizeBytes\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\"w\n" +
	"\bP2PChunk\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x03 \x01(\tR\tchunkHash\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"`\n" +
	"\vP2PChunkAck\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB8Z6github.com/saitddundar/vinctum-core/proto/p2p/v1;p2pv1b\x06proto3"

var (
	file_p2p_v1_p2p_proto_rawDescOnce sync.Once
	file_p2p_v1_p2p_proto_rawDescData []byte
)

func file_p2p_v1_p2p_proto_rawDescGZIP() []byte {
	file_p2p_v1_p2p_proto_rawDescOnce.Do(func() {
		file_p2p_v1_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_p2p_v1_p2p_proto_rawDesc), len(file_p2p_v1_p2p_proto_rawDesc)))
	})
	return file_p2p_v1_p2p_proto_rawDescData
}

var file_p2p_v1_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_p2p_v1_p2p_proto_goTypes = []any{
	(*P2PTransferHeader)(nil), // 0: p2p.v1.P2PTransferHeader
	(*P2PChunk)(nil),          // 1: p2p.v1.P2PChunk
	(*P2PChunkAck)(nil),       // 2: p2p.v1.P2PChunkAck
}
var file_p2p_v1_p2p_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_p2p_v1_p2p_proto_init() }
func file_p2p_v1_p2p_proto_init() {
	if File_p2p_v1_p2p_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_p2p_v1_p2p_proto_rawDesc), len(file_p2p_v1_p2p_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_p2p_v1_p2p_proto_goTypes,
		DependencyIndexes: file_p2p_v1_p2p_proto_depIdxs,
		MessageInfos:      file_p2p_v1_p2p_proto_msgTypes,
	}.Build()
	File_p2p_v1_p2p_proto = out.File
	file_p2p_v1_p2p_proto_goTypes = nil
	file_p2p_v1_p2p_proto_depIdxs = nil
}
