// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"
)

type Peer struct {
	NodeID    string    `json:"node_id"`
	Addrs     []string  `json:"addrs"`
	PublicKey string    `json:"public_key"`
	IsRelay   bool      `json:"is_relay"`
	LastSeen  time.Time `json:"last_seen"`
}
