// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const getPeer = `-- name: GetPeer :one
SELECT node_id, addrs, public_key, is_relay, last_seen FROM peers WHERE node_id = $1
`

func (q *Queries) GetPeer(ctx context.Context, nodeID string) (Peer, error) {
	row := q.db.QueryRow(ctx, getPeer, nodeID)
	var i Peer
	err := row.Scan(
		&i.NodeID,
		&i.Addrs,
		&i.PublicKey,
		&i.IsRelay,
		&i.LastSeen,
	)
	return i, err
}

const listPeers = `-- name: ListPeers :many
SELECT node_id, addrs, public_key, is_relay, last_seen FROM peers ORDER BY last_seen DESC
`

func (q *Queries) ListPeers(ctx context.Context) ([]Peer, error) {
	rows, err := q.db.Query(ctx, listPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Peer
	for rows.Next() {
		var i Peer
		if err := rows.Scan(
			&i.NodeID,
			&i.Addrs,
			&i.PublicKey,
			&i.IsRelay,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPeer = `-- name: UpsertPeer :exec
INSERT INTO peers (node_id, addrs, public_key, is_relay, last_seen)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (node_id) DO UPDATE
SET addrs      = EXCLUDED.addrs,
    public_key = EXCLUDED.public_key,
    is_relay   = EXCLUDED.is_relay,
    last_seen  = NOW()
`

type UpsertPeerParams struct {
	NodeID    string   `json:"node_id"`
	Addrs     []string `json:"addrs"`
	PublicKey string   `json:"public_key"`
	IsRelay   bool     `json:"is_relay"`
}

func (q *Queries) UpsertPeer(ctx context.Context, arg UpsertPeerParams) error {
	_, err := q.db.Exec(ctx, upsertPeer,
		arg.NodeID,
		arg.Addrs,
		arg.PublicKey,
		arg.IsRelay,
	)
	return err
}
