// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	GetPeer(ctx context.Context, nodeID string) (Peer, error)
	ListPeers(ctx context.Context) ([]Peer, error)
	UpsertPeer(ctx context.Context, arg UpsertPeerParams) error
}

var _ Querier = (*Queries)(nil)
